- .github/templates/azure-function-cd-template.yml
- .github/workflows/asynchronousingestor-cd.yml
- .github/workflows/businessworkflow-cd.yml
- .github/workflows/soaptojsonadapter-cd.yml
- .github/workflows/synchronousingestor-cd.yml
> remove documentation update dispatching until later

- README.md
> add context streams to readme

- NOTICE.md
> Clean up in NOTICE.md

- build/infrastructure/appi.tf
- build/infrastructure/azfun-asynchronousingestor.tf
- build/infrastructure/azfun-businessworkflow.tf
- build/infrastructure/azfun-soaptojsonadapter.tf
- build/infrastructure/azfun-synchronousingestor.tf
- build/infrastructure/evh-request-queue.tf
- build/infrastructure/kv-marketroles.tf
- build/infrastructure/providers.tf
- build/infrastructure/sb-marketroles.tf
- build/infrastructure/sqlsrv-marketroles.tf
- build/infrastructure/stor-soap-to-json-adapter-storage.tf
Fixed issue with new terraform version
> Terraform versioning

- build/infrastructure/appi.tf
- build/infrastructure/azfun-asynchronousingestor.tf
- build/infrastructure/azfun-businessworkflow.tf
- build/infrastructure/azfun-soaptojsonadapter.tf
- build/infrastructure/azfun-synchronousingestor.tf
- build/infrastructure/evh-request-queue.tf
- build/infrastructure/kv-marketroles.tf
- build/infrastructure/sb-marketroles.tf
- build/infrastructure/sqlsrv-marketroles.tf
- build/infrastructure/stor-soap-to-json-adapter-storage.tf
> update tf module version

- source/business-workflow/source/Energinet.DataHub.MarketData.EntryPoint/Energinet.DataHub.MarketData.EntryPoint.csproj
- source/business-workflow/source/Energinet.DataHub.MarketData.Infrastructure/Energinet.DataHub.MarketData.Infrastructure.csproj
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion.csproj
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/Energinet.DataHub.MarketRoles.EntryPoints.Outbox.csproj
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Processing/Energinet.DataHub.MarketRoles.EntryPoints.Processing.csproj
- source/ingestion/source/Energinet.DataHub.Ingestion.Tests/Energinet.DataHub.Ingestion.Tests.csproj
- source/shared/messaging/source/GreenEnergyHub.Messaging.Protobuf.Tests/GreenEnergyHub.Messaging.Protobuf.Tests.csproj
Combined all remaining minor nuget package version bumps from Dependabot
> Dependabot bumps combined

- .licenserc.json
> include license in license check

- .github/utilities/md-spellcheck/wordlist.txt
- .github/workflows/codecov-ci.yml
- README.md
- codecov.yml
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/Domain/CvrNumbers/CvrNumberTests.cs
Configure Codecov for unit-tests
> Configure codecov for unit tests

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/AccountingPoint.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Events/EnergySupplierChanged.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/DataAccess/IDbConnectionFactory.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/DataAccess/SqlDbConnectionFactory.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Energinet.DataHub.MarketRoles.Infrastructure.csproj
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/IntegrationEventDispatching/ChangeOfSupplier/EnergySupplierChanged.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/IntegrationEventDispatching/ChangeOfSupplier/PublishWhenEnergySupplierHasChanged.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/IntegrationEventDispatching/IIntegrationEvent.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/ChangeOfSupplier/Processing/ProcessManagerRouterTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/TestHost.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/Application/ChangeOfSupplier/Process/ChangeOfSupplierProcessManagerTests.cs
This PR adds a notification handler for generating `EnergySupplierChanged` integration event.
There might be additional metadata needed for this integration event, but this can be added later on.
> Add handler for generating and dispatching change of supplier integration event

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/ChangeOfSupplier/Validation/RequestChangeOfSupplierRuleSet.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/Common/Validation/GlnNumberMustBeValid.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/Common/Validation/GsrnNumberMustBeValidRule.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/Common/Validation/StartOfSupplyMustBeValidRule.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/Common/Validation/TranscationMustBeValidRule.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/Energinet.DataHub.MarketRoles.Application.csproj
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/BusinessRequestProcessing/Pipeline/InputValidationBehaviour.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/ChangeOfSupplier/RequestTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/SampleData.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/TestHost.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/Application/ChangeOfSupplier/Validation/RequestChangeOfSupplierRuleSetTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/Energinet.DataHub.MarketRoles.Tests.csproj
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/SampleData.cs
This PR adds input validation for request change of supplier. Input validation behaviour is also added to business processing pipeline.
Validation rules are purely based upon FluentValidation.
> Add input validation handling

- source/business-workflow/Energinet.DataHub.MarketRoles.sln
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Helpers/ConnectionStringFactory.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Helpers/CustomScriptProvider.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Helpers/EnvironmentFilter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Helpers/NamingConvention.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Helpers/ResultReporter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Helpers/ScriptComparer.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Helpers/UpgradeFactory.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Program.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/README.md
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202105051000 Initial Market Roles DB.sql
Implemented ApplyDBMigrationsApp project
added initial sql script 
* #565
> ApplyDBMigrationsApp project added

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDIMessaging/ENTSOE/CIM/ChangeOfSupplier/RequestChangeOfSupplierResultHandler.cs
> Refactor: Implement base handler to remove duplication

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/MoveIn/RequestMoveInHandler.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202105051000 Initial Market Roles DB.sql
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/Consumers/Consumer.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/Consumers/ConsumerName.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/Consumers/Events/ConsumerCreated.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/Consumers/IConsumerRepository.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/AccountingPoint.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Events/ConsumerMoveInAccepted.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/Program.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/DataAccess/Consumers/ConsumerEntityConfiguration.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/DataAccess/Consumers/ConsumerRepository.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/MoveIn/MoveInTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/SampleData.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/TestHost.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/Domain/Consumers/ConsumerTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/Domain/MeteringPoints/MoveIn/AcceptTests.cs
In this PR:
- Include consumer name in `Consumer` aggregate
- Raise `ConsumerCreated` domain event
- Create new `Consumer` if it does not already exist
> Register new consumer

- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/Program.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/Channels/NullChannel.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/MoveIn/ConsumerRegisteredTopic.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Topic.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/TopicSender.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/AzureFunctionHostConfigurationTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Energinet.DataHub.MarketRoles.IntegrationTests.csproj
Handle DI of multiple servicebus senders
* #0000
> Handle DI of multiple servicebus senders

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/ChangeOfSupplier/Processing/ProcessManagerRouter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/MoveIn/Processing/EffectuateConsumerMoveIn.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/MoveIn/Processing/EffectuateConsumerMoveInHandler.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/AccountingPoint.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Events/ConsumerMovedIn.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Events/EnergySupplierChanged.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Helpers/IntegrationEventTypeFactory.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/ChangeOfSupplier/EnergySupplierChangedIntegrationEvent.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/ChangeOfSupplier/PublishWhenEnergySupplierHasChanged.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/MoveIn/ConsumerMovedInIntegrationEvent.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/MoveIn/PublishWhenConsumerHasMovedIn.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/ChangeOfSupplier/Processing/ProcessManagerRouterTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/MoveIn/EffectuateTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/MoveIn/MoveInTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/TestHost.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/Application/ChangeOfSupplier/Process/ChangeOfSupplierProcessManagerTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/Domain/MeteringPoints/MoveIn/EffectuateTests.cs
This PR adds logic for effectuate consumer move in.
Changes:
- Add command and handler for effectuate move in including tests
- Add effectuate logic in `AccountingPoint`
- Minor refactorings
> Add logic for effectuate consumer move in

- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Common/EntryPoint.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/Program.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/Program.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/AzureFunctionHostConfigurationTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Energinet.DataHub.MarketRoles.IntegrationTests.csproj
Extracts base entrypoint and uses that in outbox and ingestion.
> extract base entrypoint

- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/Program.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/ITopicSender.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/TopicSender.cs
Implemented an interface for TopicSender.
Changed registration of topics to open generic
CreateSender method changed to be a sendmessage method, also setting the subject.
* #0000
> Open generic registration

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/MoveIn/Processing/MoveInProcessManager.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/MoveIn/Processing/MoveInProcessManagerRouter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/DataAccess/MarketRolesContext.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/DataAccess/ProcessManagers/MoveInProcessManagerEntityConfiguration.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/MoveIn/EffectuateTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/MoveIn/MoveInTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/MoveIn/Processing/MoveInProcessManagerTests.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/Application/MoveIn/Process/MoveInProcessManagerTests.cs
This PR implements a process manager for the move in business process.
Changes:
- Add `MoveInProcessManager`
- Add `MoveInProcessManagerRouter`
- Add EF core entity configuration for `MoveInProcessManager`
> Add process manager for move in

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/TopicSender.cs
> Null check on Topic

- .github/utilities/md-spellcheck/wordlist.txt
- docs/contracts.md
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/FutureEnergySupplierChangeAccepted.proto
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/FutureEnergySupplierChangeCancelled.proto
As agreed with team Joules and @Sondergaard we have renamed our contract names to better reflect future events.
* #0000
> Changed naming of contracts to be more telling

- build/infrastructure/azfun-outbox.tf
- build/infrastructure/keyvault.tf
- build/infrastructure/resource-group.tf
- build/infrastructure/sb-integration-event-shared.tf
- build/infrastructure/variables.tf
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/Program.cs
> Terraform shared servicebus

- .github/workflows/infrastructure-cd.yml
Missing terraform values on input variables.
> fix bug introduced in @2c184279945a3eb1b9a92dd0924e6f6ae7422f3a

- .github/dependabot.yml
- .github/workflows/internal-command-dispatcher-cd.yml
- .github/workflows/internal-command-dispatcher-ci.yml
- build/infrastructure/azfun-internal-command-dispatcher.tf
- source/business-workflow/Energinet.DataHub.MarketRoles.sln
- source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202105051000 Initial Market Roles DB.sql
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher/Dispatcher.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher.csproj
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher/Infrastructure/TimerTriggers/ScheduleStatus.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher/Infrastructure/TimerTriggers/TimerInfo.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher/Program.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher/host.json
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher/local.settings.sample.json
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/CommandScheduler.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/InternalCommandServiceBusDispatcher.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/QueuedInternalCommand.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/QueuedInternalCommandEntityConfiguration.cs
This PR adds Azure function (TimerTrigger) host for dispatching queued internal commands to service bus queue.
* #602
> Add internal command queue dispatcher

- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/CommandApi.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/Program.cs
> Add Command Factory including converting of XML to Composition Root

- build/infrastructure/azfun-internal-command-dispatcher.tf
Update function settings TF
* #0000
> Update internal command function settings TF

- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Processing/Program.cs
Update Processing DI registration
* #0000
> Update Processing DI registration

- build/infrastructure/azfun-internal-command-dispatcher.tf
Function Name set to correct name and not duplicate of outbox
* #0000
> Function Name set to correct name

- build/infrastructure/sb-integration-event-shared.tf
> Does this work now?

- build/infrastructure/azfun-outbox.tf
Add event message dispatch trigger to outbox settings in tf
* #0000
> Add event message dispatch trigger to outbox setting tf

- .github/workflows/internal-command-dispatcher-cd.yml
> Update function name in CD

- .github/workflows/sonarcloud.yml
This makes sonarcloud run again.
> Fix sonarcloud

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/CannotBeInStateOfClosedDownRuleErrorConverter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/ChangeOfSupplierRegisteredOnSameDateIsNotAllowedRuleErrorConverter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/CprNumberFormatRuleErrorConverter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/CvrNumberFormatRuleErrorConverter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/ProductionMeteringPointMustBeObligatedRuleErrorConverter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/SocialSecurityNumberMustBeValidRuleErrorConverter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/StartOfSupplyMustBeValidRuleErrorConverter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/VATNumberMustBeValidRuleErrorConverter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/MoveIn/RequestMoveInResultHandler.cs
Adds error conversion concept.
All error conversions are just TODO's for now - watch out for a later PR.
> add error conversion

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/Common/Validation/Consumers/SocialSecurityNumberMustBeValidRule.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/Common/Validation/Consumers/SocialSecurityNumberMustBeValidRuleError.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/Common/Validation/Consumers/VATNumberMustBeValidRule.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/Common/Validation/Consumers/VATNumberMustBeValidRuleError.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/MoveIn/Validation/RequestMoveInRuleSet.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/EventMessageDispatcher.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/Program.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/SocialSecurityNumberMustBeValidRuleErrorConverter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/VATNumberMustBeValidRuleErrorConverter.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/IIntegrationEventDispatchOrchestrator.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Services/IntegrationEventDispatchOrchestrator.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/TestHost.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests/Application/MoveIn/Validation/RequestMoveInRuleSetTests.cs
Move various components to their right home.
> Refactor: Move and reorganize components

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/ChangeOfSupplier/RequestChangeOfSupplier.cs
> Fix ingestion not recognizing change of supplier process

- source/Energinet.DataHub.MarketRoles.Application/ChangeOfSupplier/RequestChangeOfSupplier.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/Processing/Mappers/RequestChangeOfSupplierMapper.cs
> added mapper in processing for change of supplier

- build/infrastructure/azfun-outbox.tf
Topic variable update in Outbox
* #0000
> Topic variable update in Outbox

- source/Energinet.DataHub.MarketRoles.Application/ChangeOfSupplier/Processing/ChangeSupplier.cs
- source/Energinet.DataHub.MarketRoles.Application/ChangeOfSupplier/Processing/ConsumerDetails/ForwardConsumerDetails.cs
- source/Energinet.DataHub.MarketRoles.Application/ChangeOfSupplier/Processing/EndOfSupplyNotification/NotifyCurrentSupplier.cs
- source/Energinet.DataHub.MarketRoles.Application/ChangeOfSupplier/Processing/MeteringPointDetails/ForwardMeteringPointDetails.cs
- source/Energinet.DataHub.MarketRoles.Application/Common/Commands/InternalCommand.cs
- source/Energinet.DataHub.MarketRoles.Application/MoveIn/Processing/EffectuateConsumerMoveIn.cs
- source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/local.settings.sample.json
- source/Energinet.DataHub.MarketRoles.EntryPoints.Processing/Energinet.DataHub.MarketRoles.EntryPoints.Processing.csproj
- source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/Protobuf/Mappers/ChangeOfSupplier/ChangeSupplierInbound.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/Protobuf/Mappers/ChangeOfSupplier/ChangeSupplierOutbound.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/Protobuf/Mappers/ChangeOfSupplier/ForwardConsumerDetailsInbound.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/Protobuf/Mappers/ChangeOfSupplier/ForwardConsumerDetailsOutbound.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/Protobuf/Mappers/ChangeOfSupplier/ForwardMeteringPointDetailsInbound.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/Protobuf/Mappers/ChangeOfSupplier/ForwardMeteringPointDetailsOutbound.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/Protobuf/Mappers/ChangeOfSupplier/NotifyCurrentSupplierInbound.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/Protobuf/Mappers/ChangeOfSupplier/NotifyCurrentSupplierOutbound.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/Protobuf/Mappers/MoveIn/EffectuateConsumerMoveInInbound.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/InternalCommands/Protobuf/Mappers/MoveIn/EffectuateConsumerMoveInOutbound.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/Processing/Contracts/Contract.proto
- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/MoveIn/EffectuateTests.cs
> Bugfix: ProcessedDate was not set for InternalCommand when actually processed

- .github/workflows/infrastructure-cd.yml
> Update infrastructure cd

- source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Rules/ChangeEnergySupplier/MoveInRegisteredOnSameDateIsNotAllowedRule.cs
> Expand MoveInRegisteredOnSameDateIsNotAllowedRule

- source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/local.settings.sample.json
- source/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher/local.settings.sample.json
- source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/local.settings.sample.json
- source/Energinet.DataHub.MarketRoles.EntryPoints.Processing/Energinet.DataHub.MarketRoles.EntryPoints.Processing.csproj
- source/Energinet.DataHub.MarketRoles.EntryPoints.Processing/local.settings.sample.json
> Update settings samples

- source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/AccountingPoint.cs
- source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/ConsumerRegistration.cs
- source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Events/ConsumerMovedIn.cs
- source/Energinet.DataHub.MarketRoles.Tests/Domain/MeteringPoints/MoveIn/EffectuateTests.cs
> Effectuate move in and fix 1970 as defualt value

- .github/workflows/ingestion-cd.yml
- .github/workflows/internal-command-dispatcher-cd.yml
- .github/workflows/outbox-cd.yml
- .github/workflows/processing-cd.yml
> Remove Autodoc action from CD's since the doc repo is archived

- source/Energinet.DataHub.MarketRoles.Infrastructure/PostOffice/TempPostOfficeStorageClient.cs
> Changed extension name from .json to .xml in TempPostOffice

- source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Rules/ChangeEnergySupplier/MoveInRegisteredOnSameDateIsNotAllowedRule.cs
- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/ChangeOfSupplier/Processing/ProcessManagerRouterTests.cs
- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/TestHost.cs
- source/Energinet.DataHub.MarketRoles.Tests/Domain/MeteringPoints/MoveIn/AcceptTests.cs
Fixes failing integration tests.
> fix: move in integration test

- source/Energinet.DataHub.MarketRoles.Application/MoveIn/RequestMoveInHandler.cs
- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/ChangeOfSupplier/RequestTests.cs
- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/MoveIn/EffectuateTests.cs
- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/MoveIn/MoveInTests.cs
- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/TestHost.cs
> Fix move in on top of move in

- source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/AccountingPoint.cs
- source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/ConsumerRegistration.cs
Move in date is now saved in ConsumerRegistrations.
fixes #637
> fix: move in date is saved

- source/Energinet.DataHub.MarketRoles.Application/Common/Validation/GsrnNumberMustBeValidRule.cs
- source/Energinet.DataHub.MarketRoles.Domain/EnergySuppliers/GlnNumber.cs
- source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/InvalidSupplierIdRuleException.cs
- source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Rules/GlnNumberMustBeValidRule.cs
- source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Rules/GlnNumberMustBeValidRuleError.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/GlnNumberMustBeValidDomainErrorConverter.cs
- source/Energinet.DataHub.MarketRoles.Tests/Domain/GlnNumbers/GlnNumberTests.cs
> Add logic to GLN Value Object including tests

- .github/workflows/integration-test-ci.yml
- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/DatabaseFixture.cs
This PR adds an appsettings flag to determine if we should use the containerized database or local database.
> allow local db in tests

- .github/workflows/infrastructure-cd.yml
> Change to on push

- .github/workflows/infrastructure-cd.yml
> DBUP script path added

- source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/MoveIn/RequestMoveInResultHandler.cs
Made the name of the message type more useful
> Updated messageType for move in request

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Updated the version of centralized workflows used
> Updated workflows

- source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Notifications/ProductionMeteringPoint/ProductionMeteringPointCreatedInboundMapper.cs
when prod mp created event is consumed
https://app.zenhub.com/workspaces/batman-60a6105157304f00119be86e/issues/energinet-datahub/geh-metering-point/388
> Change metering type to Production on accounting point

- source/Energinet.DataHub.MarketRoles.EntryPoints.Common/MediatR/SimpleInjectorMediatorContainerExtensions.cs
- source/Energinet.DataHub.MarketRoles.EntryPoints.Common/Telemetry/EntryPointTelemetryScopeMiddleware.cs
- source/Energinet.DataHub.MarketRoles.EntryPoints.Common/Telemetry/NotificationHandlerTelemetryDecorator.cs
- source/Energinet.DataHub.MarketRoles.EntryPoints.Common/Telemetry/RequestHandlerTelemetryBehavior.cs
- source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/Program.cs
- source/Energinet.DataHub.MarketRoles.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/TestHost.cs
Logs all handlers (request and notification) to Application Insights.
> update telemetry for handlers

- source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Helpers/OutboxTypeFactory.cs
> Add event to OutboxTypeFactory

- source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/Common/ServiceBusMessageExtension.cs
Update Metadata property names to adher to ADR-008
* #0000
> Update Metadata property names to adher to ADR-008

- .github/workflows/ci.yml
> Update CI Base

- README.md
- docs/test.md
- source/Energinet.DataHub.MarketRoles.Application/AccountingPoint/MeteringPointCreated.cs
- source/Energinet.DataHub.MarketRoles.Application/AccountingPoint/MeteringPointCreatedHandler.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Notifications/MeteringPointCreated/MeteringPointCreated.proto
- source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Notifications/MeteringPointCreated/MeteringPointCreatedInboundMapper.cs
Add empty notification handler so event reciever doesn't break
* #0000
> Add empty notification handler so event reciever doesn't break

- build/infrastructure/main/func-outbox.tf
Update outbox configuration settings
* #0000
> Update outbox configuration settings

- build/infrastructure/main/func-outbox.tf
Update outbox configuration
* #0000
> Update outbox configuration

- build/infrastructure/main/alerts.tf
> change action group id to list of id's

- build/infrastructure/main/alerts.tf
> add alert for ingestion

- build/infrastructure/main/alerts.tf
> sum up in 1 alert

- build/infrastructure/main/alerts.tf
> remove one dash to much

- build/infrastructure/main/alerts.tf
> alert - Remove comment

- source/B2B.Transactions.CimMessageAdapter.Tests/MessageReceiverTests.cs
- source/B2B.Transactions.CimMessageAdapter.Tests/Stubs/ActorContextStub.cs
- source/B2B.Transactions.CimMessageAdapter/Errors/SenderAuthorizationFailed.cs
- source/B2B.Transactions.CimMessageAdapter/MessageReceiver.cs
Validate sender id matches organization of authenticated user
> Validate sender id matches organization of authenticated user

- source/B2B.Transactions.CimMessageAdapter.Tests/MessageReceiverTests.cs
- source/B2B.Transactions.CimMessageAdapter/MessageReceiver.cs
Stop processing message upon first validation error
> Stop processing message upon first validation error

- source/B2B.Transactions/DataAccess/Transaction/TransactionRepository.cs
- source/B2B.Transactions/Transactions/ITransactionRepository.cs
- source/B2B.Transactions/Transactions/RegisterTransaction.cs
> Save transaction to DB

- source/B2B.Transactions.Api/B2BCimHttpTrigger.cs
- source/B2B.Transactions.Api/B2BTransactionQueueTrigger.cs
- source/B2B.Transactions.Api/Program.cs
- source/B2B.Transactions.CimMessageAdapter.Tests/MessageReceiverTests.cs
- source/B2B.Transactions.CimMessageAdapter/MessageReceiver.cs
- source/B2B.Transactions.CimMessageAdapter/Messages/SenderAuthorizer.cs
- source/B2B.Transactions.Tests/B2B.Transactions.Tests.csproj
- source/B2B.Transactions.Tests/Infrastructure/JwtBuilder.cs
- source/B2B.Transactions.Tests/Infrastructure/JwtTokenParserTests.cs
- source/B2B.Transactions.Tests/Infrastructure/MarketActorAuthenticatorTests.cs
- source/B2B.Transactions/B2B.Transactions.csproj
- source/B2B.Transactions/Infrastructure/Authentication/Bearer/BearerAuthenticationMiddleware.cs
- source/B2B.Transactions/Infrastructure/Authentication/Bearer/ClaimsEnrichmentMiddleware.cs
- source/B2B.Transactions/Infrastructure/Authentication/Bearer/CurrentClaimsPrincipal.cs
- source/B2B.Transactions/Infrastructure/Authentication/Bearer/Errors/AuthenticationError.cs
- source/B2B.Transactions/Infrastructure/Authentication/Bearer/Errors/AuthenticationHeaderIsNotBearerToken.cs
- source/B2B.Transactions/Infrastructure/Authentication/Bearer/Errors/NoAuthenticationHeaderSet.cs
- source/B2B.Transactions/Infrastructure/Authentication/Bearer/Errors/TokenValidationFailed.cs
- source/B2B.Transactions/Infrastructure/Authentication/Bearer/JwtTokenParser.cs
- source/B2B.Transactions/Infrastructure/Authentication/Bearer/Result.cs
- source/B2B.Transactions/Infrastructure/Authentication/MarketActors/Authenticated.cs
- source/B2B.Transactions/Infrastructure/Authentication/MarketActors/MarketActorAuthenticator.cs
- source/B2B.Transactions/Infrastructure/Authentication/MarketActors/MarketActorAuthenticatorMiddleware.cs
- source/B2B.Transactions/Infrastructure/Authentication/MarketActors/MarketActorIdentity.cs
- source/B2B.Transactions/Infrastructure/Authentication/MarketActors/NotAuthenticated.cs
- source/B2B.Transactions/Infrastructure/FunctionsContextExtensions.cs
- source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/Program.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/ActorProvider.cs
Added new Authentication middelware:
- BearerAuthenticationMiddleware
- ClaimsEnrichmentMiddleware
- MarketActorAuthenticatorMiddleware
> Refactor authentication middleware

- source/B2B.Transactions.Api/B2B.Transactions.Api.csproj
- source/Energinet.DataHub.MarketRoles.EntryPoints.Common/Energinet.DataHub.MarketRoles.EntryPoints.Common.csproj
- source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher.csproj
- source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/Energinet.DataHub.MarketRoles.EntryPoints.Outbox.csproj
- source/Energinet.DataHub.MarketRoles.EntryPoints.Processing/Energinet.DataHub.MarketRoles.EntryPoints.Processing.csproj
Updated Azure.Functions.Worker Nuget packages
Azure.Functions.Worker 1.3.0 -> 1.6.0
Azure.Functions.Worker.Core 1.0.1 -> 1.4.0
> Update Azure.Functions.Worker NuGet packages

- build/infrastructure/main/func-api.tf
- source/B2B.Transactions.Api/B2BTransactionQueueTrigger.cs
- source/B2B.Transactions.Api/local.settings.sample.json
> Update connection string for SB queue trigger

- source/Energinet.DataHub.MarketRoles.EntryPoints.Common/CorrelationIdMiddleware.cs
- source/Energinet.DataHub.MarketRoles.Infrastructure/Correlation/TraceContext.cs
Added logging of trace context
> Log trace context

- source/B2B.Transactions.Infrastructure/Configuration/Correlation/CorrelationIdMiddleware.cs
Added logging to correlation/CorrelationIdMiddleware
> Added logging to correlation/CorrelationIdMiddleware

- source/B2B.Transactions.Api/Program.cs
Inject correlationcontext directly instead of using composition root
> add logging to correlationidmiddleware

- source/B2B.Transactions.Api/Program.cs
- source/B2B.Transactions.Infrastructure/Configuration/Correlation/CorrelationIdMiddleware.cs
Added logging af traceId and parentId
> Logging traceId and parentId

- source/B2B.Transactions.Infrastructure/Configuration/Correlation/CorrelationIdMiddleware.cs
> Log actual correlation id from correlationcontext

- source/B2B.Transactions.Infrastructure/Authentication/MarketActors/MarketActorAuthenticator.cs
- source/B2B.Transactions.Infrastructure/Authentication/MarketActors/MarketActorAuthenticatorMiddleware.cs
- source/B2B.Transactions.IntegrationTests/CimMessageAdapter/MessageReceiverTests.cs
- source/B2B.Transactions.IntegrationTests/Infrastructure/Authentication/MarketActors/MarketActorAuthenticatorTests.cs
> Fix role claim type name

- source/B2B.Transactions.Api/Program.cs
> Fix variable name

- source/B2B.Transactions.IntegrationTests/CimMessageAdapter/MessageReceiverTests.cs
- source/B2B.Transactions.IntegrationTests/Fixtures/DatabaseFixture.cs
- source/B2B.Transactions.IntegrationTests/Fixtures/IntegrationTestFixture.cs
- source/B2B.Transactions.IntegrationTests/TestBase.cs
- source/B2B.Transactions.IntegrationTests/TransactionHandlingTests.cs
Change database fixture to collection fixture
> Change database fixture to collection fixture

- build/infrastructure/main/func-api.tf
- source/B2B.Transactions.Api/B2BTransactionQueueTrigger.cs
- source/B2B.Transactions.Api/Program.cs
- source/B2B.Transactions.Api/RequestChangeOfSupplierMessageReceiver.cs
- source/B2B.Transactions.Api/TransactionQueueListener.cs
- source/B2B.Transactions.Api/local.settings.sample.json
> Rename environment variables

- source/B2B.Transactions.IntegrationTests/Infrastructure/OutgoingMessages/MessagePublisherTests.cs
- source/B2B.Transactions.IntegrationTests/Infrastructure/OutgoingMessages/MessagePublishingTests.cs
- source/B2B.Transactions.IntegrationTests/Transactions/TransactionBuilder.cs
Minor renames and cleanups
* #0000
> Minor renames and cleanups

- source/B2B.Transactions.CimMessageAdapter.Tests/B2B.Transactions.CimMessageAdapter.Tests.csproj
- source/B2B.Transactions.CimMessageAdapter.Tests/ResponseFactoryTests.cs
- source/B2B.Transactions.IntegrationTests/B2B.Transactions.IntegrationTests.csproj
- source/B2B.Transactions.IntegrationTests/CimMessageAdapter/MessageReceiverTests.cs
- source/B2B.Transactions.IntegrationTests/Infrastructure/Authentication/MarketActors/JwtTokenParserTests.cs
- source/B2B.Transactions.IntegrationTests/Infrastructure/Authentication/MarketActors/MarketActorAuthenticatorTests.cs
- source/B2B.Transactions.IntegrationTests/Infrastructure/OutgoingMessages/MessagePublisherTests.cs
- source/B2B.Transactions.IntegrationTests/OutgoingMessages/MessagePublishingTests.cs
- source/B2B.Transactions.IntegrationTests/Transactions/TransactionHandlingTests.cs
> Add trait categories to tests

- build/infrastructure/main/func-api.tf
- source/B2B.Transactions.Api/B2B.Transactions.Api.csproj
- source/B2B.Transactions.Api/SystemTimer.cs
- source/B2B.Transactions.Api/local.settings.sample.json
- source/B2B.Transactions.Infrastructure/SystemTime/TimeHasPassed.cs
> Add SystemTimer Function

- source/B2B.Transactions.Infrastructure/OutgoingMessageStore.cs
- source/B2B.Transactions.Infrastructure/OutgoingMessages/OutgoingMessageStore.cs
Move outgoing message store to new home
> Move outgoing message store to new home

- source/B2B.Transactions.Api/SystemTimer.cs
> Update system timer

- source/B2B.Transactions.Infrastructure/DataAccess/Outgoing/OutgoingMessageEntityConfiguration.cs
- source/B2B.Transactions.Infrastructure/OutgoingMessages/OutgoingMessageStore.cs
- source/B2B.Transactions.IntegrationTests/IncomingMessages/IncomingMessageBuilder.cs
- source/B2B.Transactions.IntegrationTests/Infrastructure/OutgoingMessages/MessagePublisherTests.cs
- source/B2B.Transactions.IntegrationTests/OutgoingMessages/MessageRequestTests.cs
- source/B2B.Transactions/IncomingMessages/IncomingMessageHandler.cs
- source/B2B.Transactions/OutgoingMessages/IOutgoingMessageStore.cs
- source/B2B.Transactions/OutgoingMessages/MessageRequestHandler.cs
- source/B2B.Transactions/OutgoingMessages/OutgoingMessage.cs
- source/B2B.Transactions/OutgoingMessages/ProcessTypesDoesNotMatchException.cs
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202240271047 Add process type.sql
Ensure requested messages have matching process types
> Ensure requested messages have matching process types

- build/infrastructure/main/func-api.tf
- source/B2B.Transactions.Api/Program.cs
- source/B2B.Transactions.Api/RequestMessageBundleTrigger.cs
- source/B2B.Transactions.Api/RuntimeEnvironment.cs
- source/B2B.Transactions.Api/local.settings.sample.json
- source/B2B.Transactions.Infrastructure/Configuration/CompositionRoot.cs
- source/B2B.Transactions/OutgoingMessages/MessageDispatcher.cs
- source/B2B.Transactions/OutgoingMessages/MessageRequestHandler.cs
Added service bus adapter to pull request messages from queue, extract list of ID's and call MessageRequestHandler
> Add message request function

- source/B2B.Transactions.Infrastructure/Configuration/CompositionRoot.cs
- source/B2B.Transactions.Infrastructure/OutgoingMessages/MessageDispatcher.cs
- source/B2B.Transactions.IntegrationTests/OutgoingMessages/MessageRequestTests.cs
- source/B2B.Transactions.IntegrationTests/TestBase.cs
- source/B2B.Transactions.IntegrationTests/TestDoubles/MessageDispatcherSpy.cs
- source/B2B.Transactions/OutgoingMessages/IMessageDispatcher.cs
- source/B2B.Transactions/OutgoingMessages/MessageRequestHandler.cs
- source/B2B.Transactions/OutgoingMessages/Result.cs
> Implement message dispatcher

- source/B2B.Transactions.Api/Program.cs
- source/B2B.Transactions.Api/SystemTimer.cs
- source/B2B.Transactions.Infrastructure/B2B.Transactions.Infrastructure.csproj
- source/B2B.Transactions.Infrastructure/Configuration/CompositionRoot.cs
- source/B2B.Transactions.Infrastructure/DataAccess/B2BContext.cs
- source/B2B.Transactions.Infrastructure/InternalCommands/CommandExecutor.cs
- source/B2B.Transactions.Infrastructure/InternalCommands/CommandScheduler.cs
- source/B2B.Transactions.Infrastructure/InternalCommands/ICommand.cs
- source/B2B.Transactions.Infrastructure/InternalCommands/ICommandScheduler.cs
- source/B2B.Transactions.Infrastructure/InternalCommands/InternalCommand.cs
- source/B2B.Transactions.Infrastructure/InternalCommands/InternalCommandAccessor.cs
- source/B2B.Transactions.Infrastructure/InternalCommands/InternalCommandProcessor.cs
- source/B2B.Transactions.Infrastructure/InternalCommands/ProcessInternalCommandsOnTimeHasPassed.cs
- source/B2B.Transactions.Infrastructure/InternalCommands/QueuedInternalCommand.cs
- source/B2B.Transactions.Infrastructure/InternalCommands/QueuedInternalCommandEntityConfiguration.cs
- source/B2B.Transactions.IntegrationTests/B2B.Transactions.IntegrationTests.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202250021330 Add internal commands table.sql
Add internal command processing
> Add internal command processing

- build/infrastructure/main/func-api.tf
- build/infrastructure/main/sb-marketroles.tf
> servicebus queue

- build/infrastructure/main/func-api.tf
- build/infrastructure/main/sb-marketroles.tf
> update queue name

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202250051030 Change internal command data type.sql
- source/Messaging.Api/Messaging.Api.csproj
> Update DB column

- source/Messaging.Api/Program.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Configuration/InternalCommands/InternalCommandProcessor.cs
- source/Messaging.IntegrationTests/Infrastructure/InternalCommands/InternalCommandProcessorTests.cs
- source/Messaging.IntegrationTests/Infrastructure/InternalCommands/TestCommand.cs
- source/Messaging.IntegrationTests/Infrastructure/InternalCommands/TestCommandHandler.cs
- source/Messaging.IntegrationTests/Messaging.IntegrationTests.csproj
- source/Messaging.IntegrationTests/TestBase.cs
> Update process internal command

- .github/actions/publish-release-contents/action.yml
- .github/workflows/ci.yml
> Remove unused functions CI

- source/Messaging.CimMessageAdapter/Messages/MessageParser.cs
- source/Messaging.CimMessageAdapter/Messages/RootElement.cs
- source/Messaging.CimMessageAdapter/Messages/XmlReaderExtensions.cs
- source/Messaging.IntegrationTests/CimMessageAdapter/Messages/BusinessMessageBuilder.cs
Taking another approach to parsing the xml elements. This new way can handle both formatted and non-formatted xml.
* #964
> Unformatted xml breaks tests

- .github/workflows/ci.yml
> Add business processing to CI again

- .github/workflows/ci.yml
> Fix naming

- .github/actions/publish-release-contents/action.yml
> Update publish release

- source/Messaging.Application/Common/Reasons/IValidationErrorTranslator.cs
- source/Messaging.Application/IncomingMessages/RequestChangeOfSupplier/RequestChangeOfSupplierHandler.cs
- source/Messaging.Infrastructure/Common/Reasons/ValidationErrorTranslator.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
This PR introduces a service for translating validation errors return by business layer to `Reason`s to be included in reject messages
> Add validation error translation

- source/Processing.Api/Program.cs
> Register trigger

- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
Reverts Energinet-DataHub/geh-market-roles#987
> Revert "Changed database instance to Singleton instead of Scoped"

- source/Messaging.Api/Program.cs
- source/Messaging.Infrastructure/Configuration/Serialization/ISerializer.cs
- source/Messaging.Infrastructure/Configuration/Serialization/Serializer.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/MoveInRequestAdapter.cs
> Refactor Http request in moveInRequestAdapter

- source/Processing.Application/Common/Validation/EnergySupplierMustBeKnownRule.cs
- source/Processing.Application/Common/Validation/MeteringPointMustBeKnownRule.cs
- source/Processing.Application/MoveIn/MoveInRequestHandler.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/ConsumerIdentifierIsRequired.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/ConsumerNameIsRequired.cs
- source/Processing.Domain/EnergySuppliers/Errors/UnknownEnergySupplier.cs
- source/Processing.Domain/MeteringPoints/Errors/UnknownAccountingPoint.cs
- source/Processing.Infrastructure/EDI/Errors/Converters/MeteringPointMustBeKnownRuleErrorConverter.cs
- source/Processing.Infrastructure/RequestAdapters/JsonMoveInAdapter.cs
- source/Processing.IntegrationTests/Application/MoveIn/MoveInTests.cs
Add unique error codes to validation errors
> Add unique error codes

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
Fixed missing "EmbeddedResource" property
> Added latest actor registry update

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Seed/202250170905 Add error code and text for invalid effective date.sql
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/EffectiveDateIsNotWithinAllowedTimePeriod.cs
- source/Processing.Tests/Domain/BusinessProcesses/MoveIn/ConsumerMoveInTests.cs
Add reason code and text for invalid time period for move in effective date
> Add reason code and text for invalid time period for move in effective date

- source/Processing.Api/Program.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/EffectiveDatePolicy.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/InvalidEffectiveDateTimeOfDay.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/TimeOfDay.cs
- source/Processing.Infrastructure/Configuration/MoveInProcessRegistrations.cs
- source/Processing.IntegrationTests/Application/TestHost.cs
- source/Processing.Tests/Domain/BusinessProcesses/MoveIn/ConsumerMoveInTests.cs
- source/Processing.Tests/Domain/BusinessProcesses/Policies/EffectiveDatePolicyTests.cs
- source/Processing.Tests/Domain/EffectiveDateFactory.cs
- source/Processing.Tests/Domain/EffectiveDatePolicyFactory.cs
- source/Processing.Tests/TestBase.cs
Move effective date time of day constraints to policy
> Move effective date time of day constraints to policy

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Seed/202250171432 Add error code and text for invalid effective date time of day.sql
Added seed script to add error code and messages for effective date invalid time of day
> Added script to add error codes and messages for wrong time of day

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
> Added script as embedded resource

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Seed/202250201055 Add gsrn reason translations.sql
Added seed script with GSRN reason translations:
- Adds reasons for 'GsrnNumberIsRequired' and 'InvalidGsrnNumber'
-  Delete non existens reasons (AccountingPointIdentifierIsRequired)
> Added seed script with GSRN reason translations

- source/Processing.Application/Common/Validation/Consumers/SocialSecurityNumberMustBeValidRuleError.cs
- source/Processing.Application/Common/Validation/Consumers/VATNumberMustBeValidRuleError.cs
- source/Processing.Application/Common/Validation/GlnNumberMustBeValidRuleError.cs
- source/Processing.Application/Common/Validation/GsrnNumberMustBeValidRuleError.cs
- source/Processing.Application/Common/Validation/StartOfSupplyMustBeValidRuleError.cs
- source/Processing.Application/Common/Validation/TransactionMustBeValidRuleError.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/ConsumerIdentifierIsRequired.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/ConsumerNameIsRequired.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/EffectiveDateIsNotWithinAllowedTimePeriod.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/GsrnNumberIsRequired.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/InvalidEffectiveDateTimeOfDay.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/InvalidGsrnNumber.cs
- source/Processing.Domain/Common/DateFormatMustBeUTCRuleError.cs
- source/Processing.Domain/Consumers/Rules/CprNumberFormatRuleError.cs
- source/Processing.Domain/Consumers/Rules/CvrNumberFormatRuleError.cs
- source/Processing.Domain/EnergySuppliers/Errors/UnknownEnergySupplier.cs
- source/Processing.Domain/MeteringPoints/Errors/UnknownAccountingPoint.cs
- source/Processing.Domain/MeteringPoints/Rules/ChangeEnergySupplier/CannotBeCurrentSupplierRuleError.cs
- source/Processing.Domain/MeteringPoints/Rules/ChangeEnergySupplier/CannotBeInStateOfClosedDownRuleError.cs
- source/Processing.Domain/MeteringPoints/Rules/ChangeEnergySupplier/ChangeOfSupplierRegisteredOnSameDateIsNotAllowedRuleError.cs
- source/Processing.Domain/MeteringPoints/Rules/ChangeEnergySupplier/EffectiveDateCannotBeInThePastRuleError.cs
- source/Processing.Domain/MeteringPoints/Rules/ChangeEnergySupplier/MeteringPointMustBeEnergySuppliableRuleError.cs
- source/Processing.Domain/MeteringPoints/Rules/ChangeEnergySupplier/MoveInRegisteredOnSameDateIsNotAllowedRuleError.cs
- source/Processing.Domain/MeteringPoints/Rules/ChangeEnergySupplier/MoveOutRegisteredOnSameDateIsNotAllowedRuleError.cs
- source/Processing.Domain/MeteringPoints/Rules/ChangeEnergySupplier/MustHaveEnergySupplierAssociatedRuleError.cs
- source/Processing.Domain/MeteringPoints/Rules/ChangeEnergySupplier/ProductionMeteringPointMustBeObligatedRuleError.cs
- source/Processing.Domain/MeteringPoints/Rules/GlnNumberMustBeValidRuleError.cs
- source/Processing.Domain/MeteringPoints/Rules/GsrnNumberMustBeValidRuleError.cs
- source/Processing.Domain/SeedWork/ValidationError.cs
Ensure validation errors implements an error code
> Ensure validation errors implements an error code

- build/infrastructure/main/func-processing.tf
- source/Contracts/AssemblyInfo.cs
- source/Contracts/Contracts.csproj
- source/Contracts/IntegrationEvents/ConsumerMovedIn.proto
- source/Energinet.DataHub.MarketRoles.sln
- source/Processing.Api/Configuration/SystemTimer.cs
- source/Processing.Api/Processing.Api.csproj
- source/Processing.Api/Program.cs
- source/Processing.Api/local.settings.sample.json
- source/Processing.Application/Common/IEventPublisher.cs
- source/Processing.Application/MoveIn/PublishEventOnConsumerMovedIn.cs
- source/Processing.Infrastructure/Configuration/EventPublishing/EventPublisher.cs
- source/Processing.Infrastructure/Configuration/EventPublishing/IMessagePublisher.cs
- source/Processing.Infrastructure/Configuration/EventPublishing/PublishEventsOnTimeHasPassed.cs
- source/Processing.Infrastructure/Configuration/EventPublishing/ServiceBusMessagePublisher.cs
- source/Processing.Infrastructure/Configuration/Outbox/IOutboxManager.cs
- source/Processing.Infrastructure/Configuration/Outbox/IOutboxMessageFactory.cs
- source/Processing.Infrastructure/Configuration/Outbox/OutboxManager.cs
- source/Processing.Infrastructure/Configuration/Outbox/OutboxMessageFactory.cs
- source/Processing.Infrastructure/Configuration/SystemTime/TimeHasPassed.cs
- source/Processing.IntegrationTests/Application/MoveIn/MoveInTests.cs
- source/Processing.IntegrationTests/Application/TestHost.cs
- source/Processing.IntegrationTests/TestDoubles/MessagePublisherStub.cs
Raise integration event when consumer move in is effectuated
> Raise integration event when consumer move in is effectuated

- source/Messaging.Api/IncomingMessages/IncomingMessageQueueListener.cs
- source/Messaging.Api/Program.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/MoveInRequestAdapter.cs
> Add logging

- build/infrastructure/main/func-processing.tf
> add sb sender cs

- build/infrastructure/main/kv-shared-resources.tf
> Update TF keyvault key name

- build/infrastructure/main/sb-marketroles.tf
> Correct manage auth rule

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202260011550 Clear outbox messages.sql
- source/Processing.Api/Program.cs
- source/Processing.Infrastructure/Processing.Infrastructure.csproj
> Clear outbox messages

- source/Processing.Infrastructure/Configuration/EventPublishingRegistration.cs
Hardcode event name in registration
> Hardcode event name in registration

- source/Processing.Api/Program.cs
- source/Processing.Infrastructure/Configuration/ApplicationAssemblies.cs
Scan for protobuf mappers in infrastructure assembly
> Scan for protobuf mappers in infrastructure assembly

- source/Processing.Api/Program.cs
- source/Processing.Infrastructure/Configuration/ApplicationAssemblies.cs
> Fix mediator registration

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202260021247 Add process id to move in transactions.sql
- source/Messaging.Application/Common/Commands/ICommand.cs
- source/Messaging.Application/Common/Commands/InternalCommand.cs
- source/Messaging.Application/Transactions/BusinessRequestResult.cs
- source/Messaging.Application/Transactions/MoveIn/CompleteMoveInTransaction.cs
- source/Messaging.Application/Transactions/MoveIn/CompleteMoveInTransactionHandler.cs
- source/Messaging.Application/Transactions/MoveIn/IMoveInTransactionRepository.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Application/Transactions/MoveIn/TransactionNotFoundException.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Configuration/InternalCommands/CommandExecutor.cs
- source/Messaging.Infrastructure/Configuration/InternalCommands/CommandScheduler.cs
- source/Messaging.Infrastructure/Configuration/InternalCommands/ICommandScheduler.cs
- source/Messaging.Infrastructure/Configuration/InternalCommands/QueuedInternalCommand.cs
- source/Messaging.Infrastructure/OutgoingMessages/NotifyMessageHub.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/MoveInRequester.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/MoveInTransactionRepository.cs
- source/Messaging.Infrastructure/Transactions/TransactionEntityConfiguration.cs
- source/Messaging.IntegrationTests/Infrastructure/InternalCommands/InternalCommandProcessorTests.cs
- source/Messaging.IntegrationTests/Infrastructure/InternalCommands/TestCommand.cs
- source/Messaging.IntegrationTests/TestBase.cs
- source/Messaging.IntegrationTests/TestDoubles/HttpClientSpy.cs
- source/Messaging.IntegrationTests/Transactions/MoveIn/CompleteMoveInTests.cs
- source/Messaging.Tests/Transactions/MoveIn/MoveInTransactionTests.cs
Add process id to move in transaction
> Add process id to move in transaction

- source/Messaging.ArchitectureTests/CompositionRootTests.cs
This removes the need for #pragma warning disable/restore.
> Set culture info for append method

- source/Messaging.Api/Program.cs
- source/Messaging.Application/Transactions/MoveIn/CompleteMoveInTransactionHandler.cs
- source/Messaging.ArchitectureTests/CompositionRootTests.cs
- source/Messaging.Infrastructure/Configuration/ApplicationAssemblies.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/OutgoingMessages/NotifyMessageHubHandler.cs
- source/Messaging.IntegrationTests/Infrastructure/InternalCommands/TestCommandHandler.cs
- source/Messaging.IntegrationTests/TestBase.cs
Fix MediatR handler registrations
> Fix MediatR handler registrations

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202260081922 Fix reason code column.sql
> Fix db migration script

- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Services/MeteringPointDbService.cs
> change to string builder

- build/infrastructure/main/func-api.tf
- build/infrastructure/main/func-processing.tf
- build/infrastructure/main/kv-shared-access-policies.tf
- build/infrastructure/main/kv-shared-resources.tf
> use keyvault references

- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Services/MeteringPointDbService.cs
> Update roles for actor sync

- source/Messaging.Application/Common/IMarketEvaluationPointProvider.cs
- source/Messaging.Application/Transactions/MoveIn/CompleteMoveInTransactionHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInException.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInNotifications.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInRequestHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Infrastructure/Configuration/MarketEvaluationPointProvider.cs
- source/Messaging.IntegrationTests/TestDoubles/MarketEvaluationPointProviderStub.cs
- source/Messaging.IntegrationTests/Transactions/MoveIn/CompleteMoveInTests.cs
Bugfix: Inform supplier only when present
> Bugfix: Inform supplier only when present

- source/Messaging.Application/OutgoingMessages/ProcessType.cs
- source/Messaging.IntegrationTests/IncomingMessages/IncomingMessageBuilder.cs
- source/Messaging.IntegrationTests/OutgoingMessages/MessageRequestTests.cs
- source/Messaging.IntegrationTests/Transactions/MoveIn/MoveInRequestHandlerTests.cs
Bugfix: Fix wrong process type code for move in
> Bugfix: Fix wrong process type code for move in

- source/Messaging.ArchitectureTests/CompositionRootTests.cs
- source/Messaging.ArchitectureTests/ReflectionHelper.cs
Re order test logic and make test cases more clear.
> Re order test

- build/infrastructure/main/func-api.tf
- build/infrastructure/main/kv-shared-resources.tf
Changed KV secret name reference from SBT to SBS
> Changed KV secret name

- build/infrastructure/main/kv-shared-resources.tf
> Changed KV seret name

- source/Messaging.Application/Transactions/MoveIn/CompleteMoveInTransactionHandler.cs
- source/Messaging.IntegrationTests/Application/IncomingMessages/IncomingMessageBuilder.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/AssertTransaction.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/CompleteMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MoveInRequestHandlerTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/SampleData.cs
> Complete move in transaction

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202260151247 Rename recipientid to receiverid.sql
- source/Messaging.Infrastructure/Configuration/DataAccess/Outgoing/OutgoingMessageEntityConfiguration.cs
- source/Messaging.IntegrationTests/AssertOutgoingMessage.cs
Rename column from RecipientId to ReceiverId to align with language used
> Rename column from RecipientId to ReceiverId to align with language used

- source/Processing.Api/Configuration/SystemTimer.cs
- source/Processing.Application/Common/IUnitOfWork.cs
- source/Processing.Application/Common/TimeEvents/DayHasPassed.cs
- source/Processing.Application/MoveIn/ProcessPendingProcesses.cs
- source/Processing.Infrastructure/BusinessRequestProcessing/Pipeline/UnitOfWorkBehaviour.cs
- source/Processing.Infrastructure/Configuration/DataAccess/UnitOfWork.cs
- source/Processing.Infrastructure/Configuration/EventPublishing/PublishEventsOnTimeHasPassed.cs
- source/Processing.Infrastructure/Configuration/SystemTime/TenSecondsHasPassed.cs
- source/Processing.Infrastructure/Integration/Notifications/NotificationReceiver.cs
- source/Processing.Infrastructure/InternalCommands/InternalCommandProcessor.cs
- source/Processing.IntegrationTests/Application/ChangeOfSupplier/Processing/Commands/ChangeSupplierTests.cs
- source/Processing.IntegrationTests/Application/MoveIn/ProcessPendingProcessesTests.cs
- source/Processing.IntegrationTests/Application/SystemDateTimeProviderStub.cs
- source/Processing.IntegrationTests/Application/TestHost.cs
- source/Processing.IntegrationTests/EffectiveDateFactory.cs
Process pending move in processes every day at midnight
> Process pending move in processes every day at midnight

- source/Messaging.Api/Configuration/SystemTimer.cs
- source/Messaging.Api/IncomingMessages/IncomingMessageQueueListener.cs
- source/Messaging.Application/Common/Commands/ICommand.cs
- source/Messaging.Application/Common/Commands/InternalCommand.cs
- source/Messaging.Application/Configuration/ISystemDateTimeProvider.cs
- source/Messaging.Application/IncomingMessages/IncomingMessage.cs
- source/Messaging.Application/Messaging.Application.csproj
- source/Messaging.Application/OutgoingMessages/MessageFactory.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInRequestHandler.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Configuration/InternalCommands/CommandScheduler.cs
- source/Messaging.Infrastructure/Configuration/SystemDateTimeProvider.cs
- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
- source/Messaging.IntegrationTests/Application/OutgoingMessages/MessageRequestTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/AssertTransaction.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/CompleteMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MoveInRequestHandlerTests.cs
- source/Messaging.IntegrationTests/Infrastructure/InternalCommands/InternalCommandProcessorTests.cs
- source/Messaging.IntegrationTests/Messaging.IntegrationTests.csproj
- source/Messaging.Tests/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierDocumentWriterTests.cs
- source/Messaging.Tests/OutgoingMessages/GenericNotificationDocumentWriterTests.cs
- source/Messaging.Tests/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierDocumentWriterTests.cs
- source/Messaging.Tests/SystemDateTimeProviderStub.cs
Convert move in request handler to use MediatR
> Convert move in request handler to use MediatR

- source/Messaging.Application/Configuration/ICommandScheduler.cs
- source/Messaging.Application/Transactions/MoveIn/FetchMeteringPointMasterData.cs
- source/Messaging.Application/Transactions/MoveIn/FetchMeteringPointMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/FetchMeteringPointMasterDataWhenAccepted.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Configuration/InternalCommands/CommandSchedulerFacade.cs
- source/Messaging.Infrastructure/Configuration/Processing/DomainEventsAccessor.cs
- source/Messaging.Infrastructure/Configuration/Processing/RaiseDomainEventsBehaviour.cs
- source/Messaging.Infrastructure/OutgoingMessages/MessageDispatcher.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/AssertQueuedCommand.cs
Fetch metering point master data when move in transaction is accepted
> Fetch metering point master data when move in transaction is accepted

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202260171349 Add MP master data forwarded.sql
- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterData.cs
- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Transactions/MoveInTransactionEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/AssertTransaction.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/CompleteMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardMeteringPointMasterDataTests.cs
- source/Messaging.Tests/Transactions/MoveIn/MoveInTransactionTests.cs
Add handling for forwarding metering point master data to new energy supplier
> Add handling for forwarding metering point master data to new energy supplier

- source/Messaging.Application/OutgoingMessages/BusinessReasonCode.cs
- source/Messaging.Application/OutgoingMessages/DocumentType.cs
- source/Messaging.Application/OutgoingMessages/ProcessType.cs
- source/Messaging.Domain/SeedWork/EnumerationType.cs
- source/Messaging.Domain/Transactions/MoveIn/IMoveInTransactionRepository.cs
- source/Messaging.Domain/Transactions/MoveIn/MoveInException.cs
- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Domain/Transactions/MoveIn/TransactionNotFoundException.cs
Move move in transaction object to domain layer
> Move move in transaction object to domain layer

- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Tests/Transactions/MoveIn/MoveInTransactionTests.cs
> Comment out condition

- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
> Register generic doc writer

- source/Messaging.Application/Common/HeaderWriter.cs
- source/Messaging.Application/Xml/SchemaStore/Schemas/urn-ediel-org-structure-confirmrequestchangeofsupplier-0-1.xsd
- source/Messaging.Application/Xml/SchemaStore/Schemas/urn-ediel-org-structure-rejectrequestchangeofsupplier-0-1.xsd
- source/Messaging.Application/Xml/SchemaStore/Schemas/urn-entsoe-eu-wgedi-codelists.xsd
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.Tests/OutgoingMessages/AssertXmlMessage.cs
Business has reported that the type value should be changed from 414 to E44
* #1113
> Changed cim type from 414 to E44

- source/Messaging.Api/Messaging.Api.csproj
- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
logging upgrade request response middleware
* #0000
> logging upgrade request responsed

- .github/actions/dotnet-prepare-outputs/action.yml
- .github/actions/publish-release-contents/action.yml
- .github/workflows/ci.yml
Utilize existing build output instead of building everything again
> Utilize existing build output

- .github/workflows/cd.yml
- .github/workflows/ci.yml
We decided to not use a new tag version for the latest change.
> Back to using 7.6.0 (tag)

- build/infrastructure/main/func-api.tf
- build/infrastructure/main/kv-shared-resources.tf
- source/Messaging.Api/Program.cs
- source/Messaging.Api/RuntimeEnvironment.cs
- source/Messaging.Api/local.settings.sample.json
- source/Messaging.Application/Transactions/MoveIn/FetchMeteringPointMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/IMeteringPointMasterDataService.cs
- source/Messaging.ArchitectureTests/CompositionRootTests.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
- source/Messaging.Infrastructure/Transactions/MoveIn/IConfig.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/RequestMasterDataConfiguration.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/RequestMeteringPointMasterData.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/RequestMeteringPointMasterDataDispatcher.cs
DI registrations missing
* #0000
> Request Metering Point Master data

- source/Messaging.Api/IncomingMessages/MasterDataResponseMetadata.cs
- source/Messaging.Api/IncomingMessages/MeteringPointMasterDataResponseListener.cs
- source/Messaging.Application/Transactions/MoveIn/FetchMeteringPointMasterDataWhenAccepted.cs
- source/Messaging.Domain/Transactions/MoveIn/Events/MoveInWasAccepted.cs
- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/RequestMeteringPointMasterDataDispatcher.cs
Part I of receiving the master data response
Next pr's contain handling of the master data and sending out message
* #0000
> Master data response I

- source/Messaging.Api/IncomingMessages/MeteringPointMasterDataResponseListener.cs
- source/Messaging.Application/MasterData/MasterDataContent.cs
- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterData.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/CompleteMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardMeteringPointMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataSampleData.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/SampleData.cs
Enqueues the master data response
Part III will have the actual sending of the message
* #0000
> Master data response II

- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterDataHandler.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardMeteringPointMasterDataTests.cs
Correct content in message to be added in part 4
* #0000
> Master-data-response III

- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterDataHandler.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardMeteringPointMasterDataTests.cs
> correct save outgoingmessage

- source/Messaging.Api/IncomingMessages/MeteringPointMasterDataResponseListener.cs
- source/Messaging.Application/MasterData/MasterDataContent.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardMeteringPointMasterDataTests.cs
> Master data response IV

- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterDataHandler.cs
> Master Data Response IV: Correlation Id change

- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterDataHandler.cs
> Master data response - few updates on properties

- .github/CODEOWNERS
> Remove dach as code owner

- source/Processing.Infrastructure/Configuration/InternalCommands/InternalCommandProcessor.cs
- source/Processing.Infrastructure/Configuration/InternalCommands/QueuedInternalCommand.cs
Bugfix: Deserialize to command type defined in mapper
> Bugfix: Deserialize to command type defined in mapper

- source/Processing.Application/AccountingPoints/CreateAccountingPoint.cs
> Add JSON constructor

- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardMeteringPointMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/SampleData.cs
> Add missing test for master data message

- source/Messaging.ArchitectureTests/CompositionRootTests.cs
- source/Messaging.ArchitectureTests/Requirement.cs
Change the test to follow the pattern for the other tests in ArchitectureTests
> Restructur test

- source/Processing.Application/Common/Queries/QueryResult.cs
- source/Processing.Application/Customers/GetCustomerMasterData/GetCustomerMasterDataQuery.cs
- source/Processing.Application/Customers/GetCustomerMasterData/GetCustomerMasterDataQueryHandler.cs
- source/Processing.IntegrationTests/Application/Customers/GetCustomerMasterData/GetCustomerMasterDataTests.cs
- source/Processing.IntegrationTests/Application/Customers/GetCustomerMasterData/SampleData.cs
Add customer master data query
> Add customer master data query

- source/Messaging.Application/OutgoingMessages/IMessageDispatcher.cs
- source/Messaging.Application/OutgoingMessages/RequestMessagesHandler.cs
- source/Messaging.Infrastructure/OutgoingMessages/MessageDispatcher.cs
- source/Messaging.Infrastructure/OutgoingMessages/MessageRequestContext.cs
- source/Messaging.Infrastructure/OutgoingMessages/NotifyMessageHub.cs
- source/Messaging.Infrastructure/OutgoingMessages/NotifyMessageHubHandler.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/RequestMessagesTests.cs
- source/Messaging.IntegrationTests/TestDoubles/MessageDispatcherSpy.cs
> Handle request message failures with a respond

- build/infrastructure/main/func-api.tf
- build/infrastructure/main/func-processing.tf
- build/infrastructure/main/sb-marketroles.tf
Added internal request/response queues for exchanging customer master data between messaging and processing
Added configuration for func-api and func-processing
> Added customer master data request and response queues

- source/Messaging.Application/OutgoingMessages/AccountingPointCharacteristics/AccountingPointCharacteristicsDocumentWriter.cs
> Add linked market evaluation point to writer

- build/infrastructure/main/func-processing.tf
- source/Processing.Api/Program.cs
- source/Processing.Api/local.settings.sample.json
- source/Processing.Infrastructure/Configuration/HealthCheckRegistration.cs
> Expand healthCheck to new queues

- .github/workflows/ci.yml
Changed reference to dotnet-solution-ci.yml to disable integration tests temporarily
> Disable integration test temporarily

- source/Messaging.Infrastructure/OutgoingMessages/NotifyMessageHub.cs
> Update constructor and constructor attrubute using

- build/infrastructure/main/alerts.tf
> Update description in alert

- source/Messaging.CimMessageAdapter/MessageReceiver.cs
> Return only empty error

- README.md
- source/Processing.Application/Customers/GetCustomerMasterData/GetCustomerMasterDataQueryHandler.cs
- source/Processing.IntegrationTests/Application/Customers/GetCustomerMasterData/GetCustomerMasterDataTests.cs
- source/Processing.IntegrationTests/Application/Customers/GetCustomerMasterData/SampleData.cs
- wordlist.txt
Customer id is hidden when customer is a private person
> Customer id is hidden when customer is a private person

- source/Messaging.Application/Transactions/MoveIn/FetchCustomerMasterData.cs
- source/Messaging.Application/Transactions/MoveIn/FetchCustomerMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/FetchCustomerMasterDataWhenAccepted.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/SampleData.cs
- source/Processing.ArchitectureTests/Application/InternalCommandTests.cs
Add command for fetching customer master data
> Add command for fetching customer master data

- source/Messaging.Api/MasterDataReceivers/MasterDataResponseMetadata.cs
- source/Messaging.Api/MasterDataReceivers/MeteringPointMasterDataResponseListener.cs
Refactor: Reorganize master data request API
> Refactor: Reorganize master data request API

- source/Messaging.Infrastructure/Configuration/InternalCommands/InternalCommandProcessor.cs
- source/Processing.Infrastructure/Configuration/InternalCommands/InternalCommandProcessor.cs
Ensure internal command processing exceptions are logged correctly in Application insights
> Ensure internal command processing exceptions are logged correctly in Application insights

- source/Messaging.Api/Messaging.Api.csproj
- source/Messaging.Api/Program.cs
- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
Updated NuGet package Energinet.DataHub.Core.Logging to version 2.2.0, to fix problem with "RequestResponseLoggingMiddleware" not supporting JSON requests.
Added call to middleware to host configuration.
> Update NuGet package and call Logging middleware

- source/Messaging.Application/Common/DocumentWriter.cs
- source/Messaging.Application/OutgoingMessages/DocumentFactory.cs
- source/Messaging.Application/OutgoingMessages/MessageFactory.cs
- source/Messaging.Application/OutgoingMessages/RequestMessagesHandler.cs
- source/Messaging.CimMessageAdapter/MessageReceiver.cs
- source/Messaging.CimMessageAdapter/Messages/IMessageParser.cs
- source/Messaging.CimMessageAdapter/Messages/JsonMessageParser.cs
- source/Messaging.CimMessageAdapter/Messages/MessageParser.cs
- source/Messaging.CimMessageAdapter/Messages/XmlMessageParser.cs
- source/Messaging.CimMessageAdapter/Response/IResponseFactory.cs
- source/Messaging.CimMessageAdapter/Response/JsonResponseFactory.cs
- source/Messaging.CimMessageAdapter/Response/ResponseFactory.cs
- source/Messaging.CimMessageAdapter/Response/XmlResponseFactory.cs
- source/Messaging.Domain/OutgoingMessages/CimFormat.cs
- source/Messaging.Domain/OutgoingMessages/IDocumentWriter.cs
- source/Messaging.Domain/OutgoingMessages/OutgoingMessageException.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/IncomingMessages/CimFormatParser.cs
- source/Messaging.IntegrationTests/CimMessageAdapter/MessageReceiverTests.cs
- source/Messaging.Tests/Application/OutgoingMessages/DocumentFactoryTests.cs
- source/Messaging.Tests/CimMessageAdapter/Messages/MessageParserTests.cs
- source/Messaging.Tests/CimMessageAdapter/Response/ResponseFactoryTests.cs
- source/Messaging.Tests/Infrastructure/IncomingMessages/CimFormatParserTests.cs
DocumentFactory can handle multiple CIM formats
> DocumentFactory can handle multiple CIM formats

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202208181332 Add actor table to BtwoB.sql
> Add actor table to b2b

- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Services/ActorSyncService.cs
- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Services/MarketRolesDbService.cs
- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/SyncActors.cs
> Sync actors to b2b

- source/Messaging.Api/OutgoingMessages/MessageRequestQueueListener.cs
- source/Messaging.Application/OutgoingMessages/DocumentFactory.cs
- source/Messaging.Application/OutgoingMessages/Requesting/IMessageRequestNotifications.cs
- source/Messaging.Application/OutgoingMessages/Requesting/RequestMessagesHandler.cs
- source/Messaging.Infrastructure/OutgoingMessages/Requesting/MessageRequestContext.cs
- source/Messaging.Infrastructure/OutgoingMessages/Requesting/MessageRequestNotifications.cs
- source/Messaging.Infrastructure/OutgoingMessages/Requesting/SendFailureNotification.cs
- source/Messaging.Infrastructure/OutgoingMessages/Requesting/SendFailureNotificationHandler.cs
- source/Messaging.Infrastructure/OutgoingMessages/Requesting/SendSuccessNotification.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/Requesting/RequestMessagesTests.cs
- source/Messaging.IntegrationTests/TestBase.cs
Request messages in specified response format
> Request messages in specified response format

- source/Messaging.Application/Messaging.Application.csproj
- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
- source/Messaging.IntegrationTests/Messaging.IntegrationTests.csproj
> Update message hub client

- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
- source/Messaging.IntegrationTests/Messaging.IntegrationTests.csproj
Upgrade message hub client package
> Upgrade message hub client package

- build/infrastructure/main/alerts.tf
> Add actor sync to alert

- source/Messaging.Application/SchemaStore/CimJsonSchemas.cs
Use Mutex when accessing global JSON schema registry to avoid concurrency issues.
> Fix concurrency issue on global schema registry

- source/Messaging.Api/Program.cs
> Disable logging middleware

- source/Messaging.Infrastructure/OutgoingMessages/NewMessageAvailableNotifier.cs
> Use legacy actor id model

- source/Messaging.Api/OutgoingMessages/MessageRequestQueueListener.cs
Add data bundle request logging
> Add data bundle request logging

- source/Messaging.Api/OutgoingMessages/MessageRequestQueueListener.cs
> Log requested response format

- source/Messaging.Api/Configuration/Middleware/Correlation/CorrelationIdMiddleware.cs
- source/Messaging.Api/Configuration/Middleware/Correlation/UserProperties.cs
> Refactor correlation id

- source/Messaging.Application/Messaging.Application.csproj
- source/Messaging.Application/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmChangeOfSupplierDocumentWriter.cs
- source/Messaging.Application/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmChangeOfSupplierJsonDocumentWriter.cs
- source/Messaging.Application/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierDocumentWriter.cs
- source/Messaging.Application/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierJsonDocumentWriter.cs
- source/Messaging.Application/SchemaStore/Schemas/Xml/urn-entsoe-eu-wgedi-codelists.xsd
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.Tests/Application/OutgoingMessages/Asserts/AssertJsonMessage.cs
- source/Messaging.Tests/Application/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierDocumentWriterTests.cs
- source/Messaging.Tests/Application/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierJsonDocumentWriterTests.cs
- source/Messaging.Tests/Application/OutgoingMessages/RejectRequestChangeOfSupplier/JsonDocumentWriterTests.cs
- source/Messaging.Tests/Application/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierDocumentWriterTests.cs
Bugfix: Update code list and type code
> Bugfix: Update code list and type code

- source/Messaging.Api/OutgoingMessages/MessageRequestQueueListener.cs
> Fix message id logging

- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Energinet.DataHub.MarketRoles.ActorRegistrySync.csproj
- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/GrantUserAccess.cs
- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Services/ActorRegistryDBService.cs
- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Services/EnergySupplyingSynchronization.cs
- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Services/MessagingSynchronization.cs
> Upgrade SQL client package

- source/Messaging.Api/Program.cs
- source/Messaging.Application/Transactions/MoveIn/ForwardCustomerMasterDataHandler.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/RequestCustomerMasterData.cs
- source/Messaging.IntegrationTests/Application/IncomingMessages/IncomingMessageBuilder.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/FetchCustomerMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardCustomerMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/SampleData.cs
- source/Messaging.IntegrationTests/EffectiveDateFactory.cs
- source/Messaging.IntegrationTests/TestBase.cs
Add integration tests for customer master data
> Add integration tests for customer master data

- build/infrastructure/main/func-api.tf
- source/Messaging.Api/MasterDataReceivers/CustomerMasterDataResponseListener.cs
> Add connection string for internal service bus namespace

- build/infrastructure/main/func-api.tf
- source/Messaging.Api/Program.cs
- source/Messaging.Api/RuntimeEnvironment.cs
- source/Messaging.Infrastructure/Configuration/MessageBus/AzureServiceBusClientConfiguration.cs
- source/Messaging.Infrastructure/Configuration/MessageBus/IServiceBusSenderAdapter.cs
- source/Messaging.Infrastructure/Configuration/MessageBus/IServiceBusSenderFactory.cs
- source/Messaging.Infrastructure/Configuration/MessageBus/ServiceBusSenderAdapter.cs
- source/Messaging.Infrastructure/Configuration/MessageBus/ServiceBusSenderFactory.cs
Add service bus client factory
> Add service bus client factory

- build/infrastructure/main/func-api.tf
> Add customer master data request queue environment variable

- source/Processing.Api/Program.cs
> Register function

- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
- source/RequestResponse/source/RequestResponse/Requests/CustomerMasterDataResponse.proto
> Change proto contract

- source/Messaging.Api/MasterDataReceivers/MeteringPointMasterDataResponseListener.cs
- source/Messaging.Api/Messaging.Api.csproj
- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
- source/Messaging.Infrastructure/Transactions/MoveIn/RequestMeteringPointMasterData.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardMeteringPointMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataSampleData.cs
- source/Messaging.IntegrationTests/EffectiveDateFactory.cs
Upgrade metering points request contracts package
> Upgrade metering points request contracts package

- source/Messaging.Application/Transactions/MoveIn/FetchCustomerMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/FetchMeteringPointMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/ICustomerMasterDataClient.cs
- source/Messaging.Application/Transactions/MoveIn/IMeteringPointMasterDataClient.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/CustomerMasterDataClient.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/MeteringPointMasterDataClient.cs
Rename master data request services to better reflect intent
> Rename master data request services to better reflect intent

- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
- source/RequestResponse/source/RequestResponse/Requests/CustomerMasterDataResponse.proto
> Fix model error

- source/Messaging.Api/MasterDataReceivers/CustomerMasterDataResponseListener.cs
- source/Messaging.Api/MasterDataReceivers/MeteringPointMasterDataResponseListener.cs
- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
Add exception handling for master data requests
> Add exception handling for master data requests

- source/Processing.Api/CustomerMasterData/CustomerMasterDataRequestListener.cs
- source/Processing.Api/Processing.Api.csproj
- source/Processing.Infrastructure/Processing.Infrastructure.csproj
> Fix response

- source/Messaging.Api/MasterDataReceivers/CustomerMasterDataResponseListener.cs
Parse response from byte array
> Parse response from byte array

- source/Messaging.Api/IncomingMessages/IncomingMessageQueueListener.cs
- source/Messaging.Api/MasterDataReceivers/CustomerMasterDataResponseListener.cs
- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
Use noda time extension for converting from timestamp
> Use noda time extension for converting from timestamp

- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Processing.Api/CustomerMasterData/CustomerMasterDataRequestListener.cs
- source/Processing.Api/Processing.Api.csproj
- source/Processing.Api/Program.cs
- source/Processing.Application/Customers/GetCustomerMasterData/GetCustomerMasterDataQueryHandler.cs
- source/Processing.Infrastructure/Processing.Infrastructure.csproj
- source/Processing.IntegrationTests/Application/Customers/GetCustomerMasterData/GetCustomerMasterDataTests.cs
- source/Processing.IntegrationTests/Application/TestHost.cs
> Change date type

- source/Messaging.Api/MasterDataReceivers/CustomerMasterDataResponseListener.cs
> Use instant

- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
- source/RequestResponse/source/RequestResponse/Requests/CustomerMasterDataResponse.proto
Include accounting point number in customer master data contract
> Include accounting point number in customer master data contract

- source/Processing.Api/CustomerMasterData/CustomerMasterDataRequestListener.cs
- source/Processing.Application/Customers/GetCustomerMasterData/GetCustomerMasterDataQueryHandler.cs
- source/Processing.Infrastructure/Processing.Infrastructure.csproj
- source/Processing.IntegrationTests/Application/Customers/GetCustomerMasterData/GetCustomerMasterDataTests.cs
Include accounting point number in customer data response
> Include accounting point number in customer data response

- source/Messaging.Api/MasterDataReceivers/CustomerMasterDataResponseListener.cs
- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
Parse accounting point number from response
> Parse accounting point number from response

- source/Messaging.Application/MasterData/CustomerMasterDataContent.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardCustomerMasterDataTests.cs
Add null guard for market evaluation point number in customer master data
> Add null guard for market evaluation point number in customer master data

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202210091043 Remove correlation id.sql
- source/Messaging.Api/Program.cs
- source/Messaging.Application/Transactions/MoveIn/ForwardCustomerMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInNotifications.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInRequestHandler.cs
- source/Messaging.Domain/OutgoingMessages/OutgoingMessage.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/Outgoing/OutgoingMessageEntityConfiguration.cs
- source/Messaging.Infrastructure/OutgoingMessages/INewMessageAvailableNotifier.cs
- source/Messaging.Infrastructure/OutgoingMessages/NewMessageAvailableNotifier.cs
- source/Messaging.IntegrationTests/AssertOutgoingMessage.cs
- source/Messaging.IntegrationTests/Infrastructure/OutgoingMessages/MessageAvailabilityPublisherTests.cs
- source/Messaging.IntegrationTests/TestDoubles/NewMessageAvailableNotifierSpy.cs
- source/Messaging.Tests/Application/OutgoingMessages/BundleTests.cs
Refactor: Remove correlation id from outgoing messages
> Refactor: Remove correlation id from outgoing messages

- source/Messaging.Api/MasterDataReceivers/CustomerMasterDataResponseListener.cs
- source/Messaging.Infrastructure/Messaging.Infrastructure.csproj
- source/Processing.Api/CustomerMasterData/CustomerMasterDataRequestListener.cs
- source/Processing.Application/Customers/GetCustomerMasterData/GetCustomerMasterDataQueryHandler.cs
- source/Processing.Infrastructure/Processing.Infrastructure.csproj
- source/Processing.IntegrationTests/Application/Customers/GetCustomerMasterData/GetCustomerMasterDataTests.cs
> Add Supply date Customer master data

- build/infrastructure/main/func-processing.tf
- source/Processing.Api/EventListeners/MarketParticipantChangedListener.cs
> Add market participantc changed event

- source/Processing.Api/EventListeners/MarketParticipantChangedListener.cs
> Change connection string to correct listener

- source/Messaging.Api/MasterDataReceivers/CustomerMasterDataResponseListener.cs
- source/Messaging.Application/MasterData/CustomerMasterDataContent.cs
- source/Messaging.Application/OutgoingMessages/CharacteristicsOfACustomerAtAnAp/CharacteristicsOfACustomerAtAnApDocumentWriter.cs
- source/Messaging.Application/OutgoingMessages/CharacteristicsOfACustomerAtAnAp/MarketActivityRecord.cs
- source/Messaging.Tests/Application/OutgoingMessages/CharacteristicsOfACustomerAtAnAP/CharacteristicsOfACustomerAtAnApDocumentWriterTests.cs
- source/Processing.Api/CustomerMasterData/CustomerMasterDataRequestListener.cs
- source/Processing.Application/Customers/GetCustomerMasterData/GetCustomerMasterDataQueryHandler.cs
- source/Processing.IntegrationTests/Application/Customers/GetCustomerMasterData/GetCustomerMasterDataTests.cs
Bugfix: Electrical heating start date is not set when no electrical heating exists
> Bugfix: Electrical heating start date is not set when no electrical heating exists

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Seed/202209151140 Insert Reasons.sql
Add missing errors to reason translation table
#1203
> Add new reasons

- source/Messaging.Api/Program.cs
- source/Messaging.Api/RuntimeEnvironment.cs
> Extend healthchecks with new queues for api

- source/Processing.Api/Program.cs
- source/Processing.Infrastructure/ActorProvider.cs
Reverts Energinet-DataHub/geh-market-roles#1298
> Revert "Remove actor provider"

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202225081326 Create index on QueuedInternalCommands.sql
Add index on processed date on queued internal commands
> Add index on processed date on queued internal commands

- source/Processing.Api/Program.cs
- source/Processing.Infrastructure/Configuration/EventPublishing/AzureServiceBus/ServiceBusMessageDispatcher.cs
- source/Processing.Infrastructure/Configuration/EventPublishingRegistration.cs
- source/Processing.IntegrationTests/Application/TestHost.cs
- source/Processing.IntegrationTests/Infrastructure/Configuration/EventPublishing/EventDispatcherTests.cs
- source/Processing.IntegrationTests/Infrastructure/Configuration/EventPublishing/ServiceBusMessageDispatcherTests.cs
- source/Processing.IntegrationTests/TestDoubles/ServiceBusSenderFactorySpy.cs
- source/Processing.IntegrationTests/TestDoubles/ServiceBusSenderFactoryStub.cs
Publish integration events to common topic
> Publish integration events to common topic

- source/Messaging.Api/EventListeners/ConsumerMovedInListener.cs
> Update consumer moved in listener

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202225081510 Drop actors table.sql
> Drop actor table

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202225081510 Drop actors table.sql
Reverts Energinet-DataHub/geh-market-roles#1316
> Revert "Drop actor table"

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202225081510 Drop actors table.sql
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202225081511 Drop actors table.sql
> Fix DB script

- source/Processing.Api/EventListeners/ActorCreatedListener.cs
Bugfix: Integration event topic variable name
> Bugfix: Integration event topic variable name

- source/Messaging.Infrastructure/OutgoingMessages/NewMessageAvailableNotifier.cs
Send data available notifications using actor id
> Send data available notifications using actor id

- build/infrastructure/main/func-api.tf
- build/infrastructure/main/func-processing.tf
- build/infrastructure/main/sbs-integration-events.tf
- source/Messaging.Api/EventListeners/MeteringPointCreatedListener.cs
- source/Messaging.Api/Messaging.Api.csproj
- source/Messaging.Application/MasterData/MarketEvaluationPoints/CreateMarketEvalationPoint.cs
- source/Processing.Api/EventListeners/MeteringPointCreatedListener.cs
- source/Processing.Api/Processing.Api.csproj
Added new MP created event listener.
Created new internal command
Updated NuGet package for MP integration events
Currently does not enqueue any commands as appropriate handler does not yet exist.
> Add meteringpoint created event listener

- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Notifications/NotifyCurrentEnergySupplierHandlerTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Notifications/NotifyGridOperatorHandlerTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Scenario.cs
Refactor: Add move in test scenario builder
> Refactor: Add move in test scenario builder

- build/infrastructure/main/sbs-market-participant-changed.tf
> Update filter on actor created

- source/Processing.Api/Program.cs
> Update variable name

- source/Messaging.Api/EventListeners/ActorCreatedListener.cs
- source/Processing.Api/EventListeners/ActorCreatedListener.cs
- source/Processing.Api/Program.cs
> Register trigger and update parse logic in actor created listeners

- source/Processing.Api/EventListeners/ActorCreatedListener.cs
> Update logging in actor created listener in business processing

- build/infrastructure/main/func-integration-service.tf
> Fix naming of integration service function

- source/IntegrationService/IntegrationService.csproj
- source/IntegrationService/Monitor/HealthCheckEndpoint.cs
> Add health check endpoint

- build/infrastructure/main/func-integration-service.tf
> Use SQL auth

- source/IntegrationService/SyncMarketEvaluationPoints.cs
Update market evaluation point id
> Update market evaluation point id

- source/Messaging.CimMessageAdapter/MessageReceiver.cs
- source/Messaging.CimMessageAdapter/Messages/RequestChangeOfSupplier/SenderAuthorizer.cs
Move sender authorizer to a new home
> Move sender authorizer to a new home

- source/Processing.Domain/Consumers/CustomerNumber.cs
- source/Processing.Domain/Consumers/InvalidCustomerNumber.cs
- source/Processing.Domain/Consumers/Rules/InvalidCustomerNumberException.cs
- source/Processing.Domain/SeedWork/BusinessRulesValidationResult.cs
- source/Processing.Tests/Domain/Consumers/CustomerNumberTests.cs
Add customer number value object
> Add customer number value object

- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Services/ActorRegistryDBService.cs
- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Services/EnergySupplyingSynchronization.cs
> Update queries for actor sync

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081402 Add customer to consumerregistration.sql
- source/Processing.Application/MoveIn/MoveInRequestHandler.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/ConsumerMoveIn.cs
- source/Processing.Domain/Consumers/Consumer.cs
- source/Processing.Domain/Consumers/Customer.cs
- source/Processing.Domain/MeteringPoints/AccountingPoint.cs
- source/Processing.Domain/MeteringPoints/ConsumerRegistration.cs
- source/Processing.Infrastructure/Configuration/DataAccess/AccountingPoints/AccountingPointEntityConfiguration.cs
- source/Processing.Infrastructure/Configuration/DataAccess/Consumers/ConsumerEntityConfiguration.cs
- source/Processing.IntegrationTests/Application/ChangeOfSupplier/RequestTests.cs
- source/Processing.IntegrationTests/Application/MoveIn/ProcessPendingProcessesTests.cs
- source/Processing.IntegrationTests/TestBase.cs
- source/Processing.Tests/Domain/BusinessProcesses/MoveIn/ConsumerMoveInTests.cs
- source/Processing.Tests/Domain/MeteringPoints/ChangeOfSupplier/AcceptTests.cs
- source/Processing.Tests/Domain/MeteringPoints/ChangeOfSupplier/CancellationTests.cs
- source/Processing.Tests/Domain/MeteringPoints/ChangeOfSupplier/EffectuateTests.cs
- source/Processing.Tests/Domain/MeteringPoints/MoveIn/EffectuateTests.cs
Include Customer in ConsumerRegistration
> Include Customer in ConsumerRegistration

- .github/CODEOWNERS
> Add Patrick as owner

- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
Bugfix: No need to throw an exception if no current energy supplier
> Bugfix: No need to throw an exception if no current energy supplier

- source/Messaging.Application/Transactions/MoveIn/ForwardCustomerMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInRequestHandler.cs
- source/Messaging.Application/Transactions/MoveIn/Notifications/MoveInNotifications.cs
- source/Messaging.Domain/OutgoingMessages/Bundle.cs
- source/Messaging.Domain/OutgoingMessages/OutgoingMessage.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/Outgoing/OutgoingMessageEntityConfiguration.cs
- source/Messaging.Infrastructure/OutgoingMessages/NewMessageAvailableNotifier.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/Requesting/RequestMessagesTests.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/Requesting/SampleData.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardCustomerMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/SampleData.cs
- source/Messaging.IntegrationTests/Infrastructure/OutgoingMessages/MessageAvailabilityPublisherTests.cs
- source/Messaging.Tests/Domain/OutgoingMessages/BundleTests.cs
Refactor: Change ReceiverId to use actor number value object
> Refactor: Change ReceiverId to use actor number value object

- .github/workflows/cd.yml
> merge workflows introduced in pr #1361

- source/Messaging.Application/Configuration/DataHubDetails.cs
- source/Messaging.Domain/OutgoingMessages/Bundle.cs
- source/Messaging.Domain/OutgoingMessages/OutgoingMessage.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/Outgoing/OutgoingMessageEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/IncomingMessages/IncomingMessageBuilder.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardCustomerMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Notifications/NotifyCurrentEnergySupplierHandlerTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Notifications/NotifyGridOperatorHandlerTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/Infrastructure/OutgoingMessages/MessageAvailabilityPublisherTests.cs
- source/Messaging.Tests/Domain/OutgoingMessages/BundleTests.cs
Refactor: Change SenderId to use actor number value object
> Refactor: Change SenderId to use actor number value object

- source/Processing.Application/MoveIn/MoveInRequestHandler.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/CustomerMoveIn.cs
- source/Processing.Domain/BusinessProcesses/MoveIn/Errors/CustomerMustBeDifferentFromCurrentCustomer.cs
- source/Processing.Domain/MeteringPoints/AccountingPoint.cs
- source/Processing.Domain/MeteringPoints/Rules/MoveIn/CustomerMustBeDifferentFromCurrentCustomerRule.cs
- source/Processing.IntegrationTests/Application/MoveIn/ProcessPendingProcessesTests.cs
- source/Processing.Tests/Domain/BusinessProcesses/MoveIn/ConsumerMoveInTests.cs
- source/Processing.Tests/Domain/MeteringPoints/ChangeOfSupplier/AcceptTests.cs
- source/Processing.Tests/Domain/MeteringPoints/ChangeOfSupplier/CancellationTests.cs
- source/Processing.Tests/Domain/MeteringPoints/ChangeOfSupplier/EffectuateTests.cs
- source/Processing.Tests/Domain/MeteringPoints/MoveIn/EffectuateTests.cs
> Customer must be a new one on move in

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081405 Add grid operator message delivery state.sql
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/AssertTransaction.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.Tests/Domain/Transactions/MoveIn/MoveInTransactionTests.cs
Set default message delivery state for customer master data for the grid operator
> Set default message delivery state for customer master data for the grid operator

- source/Messaging.Api/MasterDataReceivers/CustomerMasterDataResponseListener.cs
- source/Messaging.Api/MasterDataReceivers/MeteringPointMasterDataResponseListener.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/ForwardCustomerMasterData.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/ForwardCustomerMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/ForwardMeteringPointMasterData.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/ForwardMeteringPointMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/SendCustomerMasterDataToGridOperator.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/SendCustomerMasterDataToGridOperatorHandler.cs
- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Transactions/MoveInTransactionEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/ForwardCustomerMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/ForwardMeteringPointMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/SendCustomerMasterDataToGridOperatorTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/SendCustomerMasterDataToGridOperatorTests.cs
Customer master data for grid operator is delivered
> Customer master data for grid operator is delivered

- source/Messaging.Application/Transactions/MoveIn/ForwardCustomerMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInRequestHandler.cs
- source/Messaging.Application/Transactions/MoveIn/Notifications/MoveInNotifications.cs
- source/Messaging.Domain/Actors/MarketRole.cs
- source/Messaging.Domain/Actors/MarketRoles.cs
- source/Messaging.Domain/OutgoingMessages/Bundle.cs
- source/Messaging.Domain/OutgoingMessages/OutgoingMessage.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/Outgoing/OutgoingMessageEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/ForwardCustomerMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Notifications/NotifyCurrentEnergySupplierHandlerTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Notifications/NotifyGridOperatorHandlerTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/Infrastructure/OutgoingMessages/MessageAvailabilityPublisherTests.cs
- source/Messaging.Tests/Domain/OutgoingMessages/BundleTests.cs
Refactor: Encapsulate market roles in value object
> Refactor: Encapsulate market roles in value object

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081406 Add customer master data.sql
- source/Messaging.Api/MasterDataReceivers/CustomerMasterDataResponseListener.cs
- source/Messaging.Application/Transactions/MoveIn/SetCustomerMasterData.cs
- source/Messaging.Application/Transactions/MoveIn/SetCustomerMasterDataHandler.cs
- source/Messaging.Domain/Transactions/MoveIn/CustomerMasterData.cs
- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/B2BContext.cs
- source/Messaging.Infrastructure/Transactions/MoveInTransactionEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/AssertTransaction.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/SetCustomerMasterDataTests.cs
- source/Messaging.IntegrationTests/Fixtures/DatabaseFixture.cs
Store customer master data with move in transaction
> Store customer master data with move in transaction

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Seed/202210071000 Insert Reasons.sql
> Reason translation added for customer number must be different

- source/Messaging.Application/Messaging.Application.csproj
- source/Messaging.Application/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/MarketActivityRecord.cs
- source/Messaging.Application/SchemaStore/Schemas/Xml/urn-ediel-org-structure-rejectrequestchangeaccountingpointcharacteristics-0-1.xsd
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/RejectRequestChangeAccountingPointCharacteristicsDocumentWriter.cs
- source/Messaging.Tests/Infrastructure/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/RejectRequestChangeAccountingPointCharacteristicsDocumentWriterTests.cs
Added new document writer
Added relevant XML schema to schema store
Added test to verify that generated output complies with schema
> Add document writer for RejectRequestChangeAccountingPointCharacteristics

- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/CustomerMasterDataMessageFactory.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/SendCustomerMasterDataToEnergySupplierHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/SendCustomerMasterDataToGridOperatorHandler.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/SendCustomerMasterDataToGridOperatorTests.cs
Customer master data message for grid operator is delivered
> Customer master data message for grid operator is delivered

- build/infrastructure/main/kv-shared-resources.tf
- build/infrastructure/main/sb-domain-relay-queues.tf
[Task Reference](https://app.zenhub.com/workspaces/batman-60a6105157304f00119be86e/issues/energinet-datahub/geh-market-roles/1386)
> Create queue for create_metering_point_transactions

- build/infrastructure/main/func-api.tf
- source/Messaging.Api/IncomingMessages/CreateMeteringPointTransactionsQueueListener.cs
depend on #1394 
[Task Reference](https://app.zenhub.com/workspaces/batman-60a6105157304f00119be86e/issues/energinet-datahub/geh-market-roles/1383)
> Consume create metering point transactions

- source/Messaging.Api/IncomingMessages/RequestChangeAccountingPointCharacteristicsMessageReceiver.cs
Add new HTTP trigger endpoint for RequestChangeAccountingPointCharacteristics.
> Add endpoint for create metering point

- source/Messaging.CimMessageAdapter/Response/ResponseMessage.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/IncomingMessages/RequestChangeOfSupplier/JsonMessageParser.cs
- source/Messaging.Infrastructure/IncomingMessages/RequestChangeOfSupplier/XmlMessageParser.cs
- source/Messaging.Infrastructure/IncomingMessages/Response/JsonResponseFactory.cs
- source/Messaging.Infrastructure/IncomingMessages/Response/XmlResponseFactory.cs
- source/Messaging.Infrastructure/IncomingMessages/RootElement.cs
- source/Messaging.Infrastructure/IncomingMessages/XmlReaderExtensions.cs
- source/Messaging.Tests/CimMessageAdapter/Messages/RequestChangeOfSupplier/MessageParserTests.cs
- source/Messaging.Tests/CimMessageAdapter/Response/JsonResponseFactoryTests.cs
- source/Messaging.Tests/CimMessageAdapter/Response/ResponseFactoryTests.cs
- source/Messaging.Tests/CimMessageAdapter/Response/XmlResponseFactoryTests.cs
Move objects to infrastructure
> Move objects to infrastructure

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Seed/202210111000 Cancel processes.sql
Cancel processes without a corresponding supplier registration
> Cancel processes without a corresponding supplier registration

- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Configuration/MoveInConfiguration.cs
- source/Processing.Api/Program.cs
- source/Processing.Infrastructure/Configuration/MoveInProcessRegistrations.cs
- source/Processing.IntegrationTests/TestBase.cs
> Change move in policy

- source/Messaging.Api/IncomingMessages/RequestChangeCustomerCharacteristicsMessageReceiver.cs
Added new HTTP trigger for RequestChangeCustomerCharacteristics
> Added new HTTP trigger for RequestChangeCustomerCharacteristics

- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/CustomerMasterDataMessageFactory.cs
- source/Messaging.Infrastructure/OutgoingMessages/CharacteristicsOfACustomerAtAnAp/CharacteristicsOfACustomerAtAnApDocumentWriter.cs
- source/Messaging.Infrastructure/OutgoingMessages/Common/Xml/DocumentWriter.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/SendCustomerMasterDataToGridOperatorTests.cs
- source/Messaging.Tests/Infrastructure/OutgoingMessages/Asserts/AssertXmlDocument.cs
- source/Messaging.Tests/Infrastructure/OutgoingMessages/CharacteristicsOfACustomerAtAnAP/CharacteristicsOfACustomerAtAnApDocumentWriterTests.cs
Include missing values in customer master data document for the grid operator
> Include missing values in customer master data document for the grid operator

- source/Messaging.Application/IncomingMessages/RequestChangeAccountPointCharacteristics/MarketActivityRecord.cs
- source/Messaging.Application/IncomingMessages/RequestChangeCustomerCharacteristics/MarketActivityRecord.cs
- source/Messaging.Application/IncomingMessages/RequestChangeCustomerCharacteristics/RequestChangeCustomerCharacteristicIncomingDocument.cs
- source/Messaging.Application/IncomingMessages/RequestChangeCustomerCharacteristics/RequestChangeCustomerCharacteristicsTransaction.cs
- source/Messaging.Application/Messaging.Application.csproj
- source/Messaging.Application/SchemaStore/Schemas/Xml/urn-ediel-org-structure-requestchangecustomercharacteristics-0-1.xsd
- source/Messaging.CimMessageAdapter/Messages/RequestChangeCustomerCharacteristics/MessageParser.cs
- source/Messaging.Infrastructure/IncomingMessages/MessageHeaderExtractor.cs
- source/Messaging.Infrastructure/IncomingMessages/RequestChangeAccountingPointCharacteristics/XmlMessageParser.cs
- source/Messaging.Infrastructure/IncomingMessages/RequestChangeCustomerCharacteristics/XmlMessageParser.cs
- source/Messaging.Infrastructure/IncomingMessages/RequestChangeOfSupplier/XmlMessageParser.cs
- source/Messaging.Tests/CimMessageAdapter/Messages/RequestChangeCustomerCharacteristics/MessageParserTests.cs
- source/Messaging.Tests/CimMessageAdapter/Messages/xml/RequestChangeCustomerCharacteristics.xml
- source/Messaging.Tests/Messaging.Tests.csproj
> Document parser request change of customer characteristics

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081407 Rename outgoing message column.sql
- source/Messaging.Application/OutgoingMessages/IOutgoingMessageStore.cs
- source/Messaging.Domain/OutgoingMessages/OutgoingMessage.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/Outgoing/OutgoingMessageEntityConfiguration.cs
- source/Messaging.Infrastructure/OutgoingMessages/OutgoingMessageStore.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/Requesting/RequestMessagesTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/Assertions/AssertOutgoingMessage.cs
Refactor: Rename to OriginalMessageId to TransactionId
> Refactor: Rename to OriginalMessageId to TransactionId

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081408 Add temp discriminator column.sql
- source/Messaging.Domain/OutgoingMessages/AccountingPointCharacteristics/AccountingPointCharacteristicsMessage.cs
- source/Messaging.Domain/OutgoingMessages/CharacteristicsOfACustomerAtAnAp/CharacteristicsOfACustomerAtAnApMessage.cs
- source/Messaging.Domain/OutgoingMessages/ConfirmRequestChangeAccountingPointCharacteristics/ConfirmRequestChangeAccountingPointCharacteristicsMessage.cs
- source/Messaging.Domain/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierMessage.cs
- source/Messaging.Domain/OutgoingMessages/DocumentType.cs
- source/Messaging.Domain/OutgoingMessages/GenericNotification/GenericNotificationMessage.cs
- source/Messaging.Domain/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/RejectRequestChangeAccountingPointCharacteristicsMessage.cs
- source/Messaging.Domain/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierMessage.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/B2BContext.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/Outgoing/OutgoingMessageEntityConfiguration.cs
Refactor: Add concrete outgoing messages
> Refactor: Add concrete outgoing messages

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081408 Add requested by actor number.sql
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081409 Add requested by actor number.sql
- source/Messaging.Application/Transactions/MoveIn/MoveInRequestHandler.cs
- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Infrastructure/Transactions/MoveInTransactionEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/AssertTransaction.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Scenario.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/WhenAConsumerHasMovedInTests.cs
- source/Messaging.Tests/Domain/Transactions/MoveIn/MoveInTransactionTests.cs
- source/Messaging.Tests/Domain/Transactions/MoveIn/SampleData.cs
Add requesting actor number to the move in transaction
> Add requesting actor number to the move in transaction

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081409 Add requested by actor number.sql
- source/Messaging.Application/Transactions/MoveIn/MoveInRequestHandler.cs
- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Infrastructure/Transactions/MoveInTransactionEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/AssertTransaction.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Scenario.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/WhenAConsumerHasMovedInTests.cs
- source/Messaging.Tests/Domain/Transactions/MoveIn/MoveInTransactionTests.cs
- source/Messaging.Tests/Domain/Transactions/MoveIn/SampleData.cs
Reverts Energinet-DataHub/geh-market-roles#1421
> Revert "Add requesting actor number to the move in transaction"

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081409 Add requesting actor number to move in transaction.sql
Include actor number of requesting actor to move in transaction
> Include actor number of requesting actor to move in transaction

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Messaging.Application/Transactions/MoveIn/MoveInRequestHandler.cs
- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Infrastructure/Transactions/MoveInTransactionEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/AssertTransaction.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Scenario.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/WhenAConsumerHasMovedInTests.cs
- source/Messaging.Tests/Domain/Transactions/MoveIn/MoveInTransactionTests.cs
- source/Messaging.Tests/Domain/Transactions/MoveIn/SampleData.cs
Add actor number of requesting energy supplier
> Add actor number of requesting energy supplier

- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
- source/RequestResponse/source/RequestResponse/Requests/UpdateCustomerDataRequest.proto
Added proto file for update customer data request
> Added proto file for update customer data request

- source/Messaging.Api/IncomingMessages/RequestChangeOfCustomerCharacteristicsTransactionQueueListener.cs
- source/Messaging.Api/IncomingMessages/RequestChangeOfSupplierTransactionQueueListener.cs
Add request change of customer characteristics transaction queue listener
> Add request change of customer characteristics transaction queue listener

- source/Processing.IntegrationTests/Application/SampleData.cs
> Change sample data to use date factory

- source/Messaging.Application/Transactions/MoveIn/UpdateCustomer/UpdateCustomerMasterData.cs
- source/Messaging.Application/Transactions/MoveIn/UpdateCustomer/UpdateCustomerMasterDataHandler.cs
- source/Messaging.Domain/Transactions/MoveIn/IMoveInTransactionRepository.cs
- source/Messaging.Domain/Transactions/MoveIn/TransactionNotFoundException.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/MoveInTransactionRepository.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/SampleData.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/UpdateCustomerMasterDataTests.cs
Throw if requested move in transaction does not exist
> Throw if requested move in transaction does not exist

- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
- source/RequestResponse/source/RequestResponse/Requests/UpdateCustomerDataRequest.proto
> Protobuf contract update for customer master data request (alpha release)

- source/Messaging.Application/SchemaStore/JsonSchemaProvider.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Configuration/IncomingMessageParsingServices.cs
- source/Messaging.Infrastructure/IncomingMessages/RequestChangeOfSupplier/JsonMessageParser.cs
- source/Messaging.Tests/CimMessageAdapter/Messages/RequestChangeOfSupplier/MessageParserTests.cs
- source/Messaging.Tests/Infrastructure/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierJsonDocumentWriterTests.cs
- source/Messaging.Tests/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/JsonDocumentWriterTests.cs
> Bugfix: Schema validation

- source/Messaging.Infrastructure/Configuration/IncomingMessageParsingServices.cs
> Fix registration

- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Energinet.DataHub.MarketRoles.ActorRegistrySync.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Messaging.Application/Messaging.Application.csproj
- source/Messaging.IntegrationTests/Messaging.IntegrationTests.csproj
- source/Processing.Infrastructure/Processing.Infrastructure.csproj
> Upgrade SQL client packages

- source/Messaging.Api/Program.cs
- source/Messaging.Api/RuntimeEnvironment.cs
- source/Messaging.Application/OutgoingMessages/IEnqueuedMessages.cs
- source/Messaging.Application/OutgoingMessages/Peek/BundleConfiguration.cs
- source/Messaging.Application/OutgoingMessages/Peek/IBundleConfiguration.cs
- source/Messaging.Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Configuration/Processing/EnqueueOutgoingMessagesBehaviour.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/EnqueuedMessages.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/Messaging.IntegrationTests/Assertions/AssertXmlMessage.cs
- source/Messaging.IntegrationTests/Factories/ConsumerFactory.cs
- source/Messaging.IntegrationTests/Factories/EffectiveDateFactory.cs
- source/Messaging.IntegrationTests/TestBase.cs
- source/Messaging.IntegrationTests/TestDoubles/BundleConfigurationStub.cs
Ensure maximum number of payloads in a bundle is not exceeded
> Ensure maximum number of payloads in a bundle is not exceeded

- source/Messaging.IntegrationTests/Fixtures/DatabaseFixture.cs
- source/Messaging.IntegrationTests/TestBase.cs
Add option to replace hard coded SQL DB ConnectingString using
the environment variable named:  B2B_MESSAGING_CONNECTION_STRING
> Messaging IntegrationTests connection string

- connectionString.patch
- source/Messaging.Api/OutgoingMessages/PeekRequestListener.cs
- source/Messaging.Application/OutgoingMessages/IEnqueuedMessages.cs
- source/Messaging.Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/EnqueuedMessages.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/SampleData.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/Messaging.IntegrationTests/Factories/TestDataBuilder.cs
- source/Messaging.IntegrationTests/TestBase.cs
- source/Messaging.IntegrationTests/TestDoubles/HttpClientSpy.cs
Bundled message contains payloads for the requested receiver role
> Bundled message contains payloads for the requested receiver role

- source/Messaging.Application/OutgoingMessages/IEnqueuedMessages.cs
- source/Messaging.Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/Messaging.Domain/OutgoingMessages/Bundle.cs
- source/Messaging.Domain/OutgoingMessages/DocumentType.cs
- source/Messaging.Domain/OutgoingMessages/Peek/EnqueuedMessage.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/SqlDbConnectionFactory.cs
- source/Messaging.Infrastructure/Configuration/Processing/EnqueueOutgoingMessagesBehaviour.cs
- source/Messaging.Infrastructure/OutgoingMessages/OutgoingMessageEnqueuer.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/EnqueuedMessages.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/Messaging.IntegrationTests/Assertions/AssertXmlMessage.cs
Bundle messages by process type
> Bundle by process type

- source/Messaging.Api/Program.cs
- source/Messaging.Application/OutgoingMessages/Peek/IPeekedMessageRepository.cs
- source/Messaging.Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/Messaging.Application/OutgoingMessages/Peek/PeekedMessageRepository.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/Messaging.IntegrationTests/TestBase.cs
- source/Messaging.IntegrationTests/TestDoubles/PeekedMessageRepositoryStub.cs
Return same bundle if not already dequeued
> Return same bundle if not dequeued

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202227101327 Add MessageId column to bundlestore.sql
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202227101328 Add MessageIdsIncluded column to bundlestore.sql
- source/Messaging.Application/OutgoingMessages/Dequeue/DequeueRequestHandler.cs
- source/Messaging.Application/OutgoingMessages/Peek/BundleStore.cs
- source/Messaging.Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/Messaging.Domain/OutgoingMessages/Bundle.cs
- source/Messaging.Domain/OutgoingMessages/BundleId.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/OutgoingMessages/Dequeue/DequeueConfiguration.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenADequeueIsRequestedTests.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
> Message dequeue

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202227101329 Add EnqueuedMessages table.sql
- source/Messaging.Application/OutgoingMessages/Peek/BundleStore.cs
- source/Messaging.Infrastructure/OutgoingMessages/OutgoingMessageEnqueuer.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/EnqueuedMessages.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenADequeueIsRequestedTests.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenOutgoingMessagesAreCreatedTests.cs
- source/Messaging.IntegrationTests/Fixtures/DatabaseFixture.cs
Implement single EnqueuedMessages table to replace actor specific ActorMessages tables
> Enqueued message repository in single table

- .github/CODEOWNERS
Update geh-market-roles codeowners
> Update geh-market-roles codeowners

- source/Messaging.Infrastructure/OutgoingMessages/PublishNewMessagesOnTimeHasPassed.cs
Control message publishing enablement using feature flag
> Control message publishing enablement using feature flag

- source/Messaging.Api/OutgoingMessages/DequeueRequestListener.cs
Change authorization mode to anonymous to support bearer authentication
> Change authorization mode to anonymous to support bearer authentication

- source/Messaging.Application/OutgoingMessages/Peek/BundleStore.cs
- source/Messaging.Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
Unregister bundle if no messages are available
> Unregister bundle if no messages are available

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202227101330 Remove actor role from bundle store.sql
- source/Messaging.Api/OutgoingMessages/PeekRequestListener.cs
- source/Messaging.Application/OutgoingMessages/IEnqueuedMessages.cs
- source/Messaging.Application/OutgoingMessages/Peek/BundleStore.cs
- source/Messaging.Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/Messaging.Domain/OutgoingMessages/BundleId.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/EnqueuedMessages.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenADequeueIsRequestedTests.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
Remove actor role as a parameter for peeking message since it is not part of the use case
Remove actor role as a parameter for peeking messages since it is not part of the use case
> Remove actor role as a parameter for peeking messages

- source/Messaging.Application/Configuration/Authentication/MarketActorIdentity.cs
- source/Messaging.IntegrationTests/Infrastructure/Authentication/MarketActors/MarketActorAuthenticatorTests.cs
> Remove obsolete Role property

- source/Messaging.Api/SendAggregatedTimeSeriesListener.cs
- source/Messaging.Domain/OutgoingMessages/NotifyAggregatedMeasureData/TimeSeries.cs
- source/Messaging.Infrastructure/Transactions/AggregatedTimeSeries/TimeSeriesDto.cs
Add test http endpoint for sending aggregated times to grid operator
> Add test http endpoint for sending aggregated times to grid operator

- source/Messaging.Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregatedTimeSeriesMessage.cs
- source/Messaging.Domain/Transactions/AggregatedTimeSeries/AggregatedTimeSeriesResult.cs
- source/Messaging.Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataMessageWriter.cs
- source/Messaging.Infrastructure/Transactions/AggregatedTimeSeries/AggregatedTimeSeriesResultDto.cs
- source/Messaging.Infrastructure/Transactions/AggregatedTimeSeries/FakeAggregatedTimeSeriesResults.cs
- source/Messaging.IntegrationTests/Application/Transactions/AggregatedTimeSeries/SampleData.cs
- source/Messaging.IntegrationTests/Application/Transactions/AggregatedTimeSeries/SendAggregatedTimeSeriesTests.cs
- source/Messaging.Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
Refactor: Calculate period time interval from the list of points
> Refactor: Calculate period time interval from the list of points

- source/Messaging.Domain/OutgoingMessages/MessageType.cs
- source/Messaging.Domain/OutgoingMessages/Peek/MessageCategory.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
Rename to align with the business language
> Rename to align with the business language

- source/Messaging.Application/Transactions/AggregatedTimeSeries/SendAggregatedTimeSeriesHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/ForwardMeteringPointMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInRequestHandler.cs
- source/Messaging.Application/Transactions/MoveIn/Notifications/MoveInNotifications.cs
- source/Messaging.Domain/OutgoingMessages/AccountingPointCharacteristics/AccountingPointCharacteristicsMessage.cs
- source/Messaging.Domain/OutgoingMessages/CharacteristicsOfACustomerAtAnAp/CharacteristicsOfACustomerAtAnApMessage.cs
- source/Messaging.Domain/OutgoingMessages/ConfirmRequestChangeAccountingPointCharacteristics/ConfirmRequestChangeAccountingPointCharacteristicsMessage.cs
- source/Messaging.Domain/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierMessage.cs
- source/Messaging.Domain/OutgoingMessages/GenericNotification/GenericNotificationMessage.cs
- source/Messaging.Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregatedTimeSeriesMessage.cs
- source/Messaging.Domain/OutgoingMessages/OutgoingMessage.cs
- source/Messaging.Domain/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/RejectRequestChangeAccountingPointCharacteristicsMessage.cs
- source/Messaging.Domain/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierMessage.cs
- source/Messaging.Domain/Transactions/AggregatedTimeSeries/AggregatedTimeSeriesTransaction.cs
- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Domain/Transactions/TransactionId.cs
- source/Messaging.Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataMessageWriter.cs
- source/Messaging.Infrastructure/OutgoingMessages/OutgoingMessageEntityConfiguration.cs
- source/Messaging.Infrastructure/OutgoingMessages/OutgoingMessageStore.cs
- source/Messaging.Infrastructure/Transactions/AggregatedTimeSeries/AggregatedTimeSeriesTransactionEntityConfiguration.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/MoveInTransactionRepository.cs
- source/Messaging.Infrastructure/Transactions/MoveInTransactionEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/AggregatedTimeSeries/SampleData.cs
- source/Messaging.IntegrationTests/Application/Transactions/AggregatedTimeSeries/SendAggregatedTimeSeriesTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Scenario.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/WhenAConsumerHasMovedInTests.cs
- source/Messaging.Tests/Domain/OutgoingMessages/BundleTests.cs
- source/Messaging.Tests/Domain/OutgoingMessages/RejectRequestChangeOfSupplierMessageTests.cs
- source/Messaging.Tests/Domain/Transactions/MoveIn/MoveInTransactionTests.cs
- source/Messaging.Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
Ensure time series id corresponds to transaction id
> Ensure time series id corresponds to transaction id

- source/Messaging.Application/Transactions/AggregatedTimeSeries/IGridAreaLookup.cs
- source/Messaging.Application/Transactions/AggregatedTimeSeries/SendAggregatedTimeSeriesHandler.cs
- source/Messaging.Domain/Transactions/AggregatedTimeSeries/AggregatedTimeSeriesResult.cs
- source/Messaging.Domain/Transactions/AggregatedTimeSeries/AggregatedTimeSeriesTransaction.cs
- source/Messaging.Infrastructure/Configuration/SendAggregatedTimeSeriesConfiguration.cs
- source/Messaging.Infrastructure/Transactions/AggregatedTimeSeries/AggregatedTimeSeriesResultDto.cs
- source/Messaging.Infrastructure/Transactions/AggregatedTimeSeries/FakeAggregatedTimeSeriesResults.cs
- source/Messaging.Infrastructure/Transactions/AggregatedTimeSeries/FakeGridAreaLookup.cs
- source/Messaging.IntegrationTests/Application/Transactions/AggregatedTimeSeries/SendAggregatedTimeSeriesTests.cs
Lookup the grid operator number via lookup service
> Lookup the grid operator number via lookup service

- source/Messaging.Infrastructure/Configuration/MessageBus/IServiceBusSenderAdapter.cs
- source/Messaging.Infrastructure/Configuration/MessageBus/ServiceBusSenderAdapter.cs
- source/Messaging.Infrastructure/Configuration/MessageBus/ServiceBusSenderFactory.cs
- source/Messaging.Infrastructure/IncomingMessages/MessageQueueDispatcher.cs
- source/Messaging.IntegrationTests/TestDoubles/ServiceBusSenderSpy.cs
Fix message queue dispatcher to handle multiple message simultaneously
> Message queue dispatcher fix

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202227101334 Fix aggregations message type.sql
> Fix aggregations message type

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202227101335 Cleanup enqueued messages.sql
> Cleanup enqueued messages

- source/Messaging.Api/Program.cs
- source/Messaging.Api/RuntimeEnvironment.cs
- source/Messaging.ArchitectureTests/CompositionRootTests.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.Infrastructure/Configuration/MoveInConfiguration.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/FakeCustomerMasterDataClient.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/FakeMeteringPointMasterDataClient.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/FakeMoveInRequester.cs
- source/Messaging.IntegrationTests/TestBase.cs
Replace external service clients with fake implementations
> Replace external service clients with fake implementations

- source/Messaging.Api/setup/README.md
- source/Messaging.Api/setup/azure-resource-create-functions.ps1
- source/Messaging.Api/setup/setupazure.ps1
- source/Messaging.PerformanceTest/Actors/ActorService.cs
- source/Messaging.PerformanceTest/Controllers/PeekDequeuePerformanceTestController.cs
- source/Messaging.PerformanceTest/k6/runtest.sh
- wordlist.txt
> Messaging.API developer setup

- source/Messaging.Application/OutgoingMessages/Dequeue/DequeueRequestHandler.cs
- source/Messaging.Application/OutgoingMessages/Peek/IBundleStore.cs
- source/Messaging.Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/BundleStore.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/PeekConfiguration.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
Moved BundleStore to infrastructure layer instead, and inject interface
> Move BundleStore to infrastructure and inject interface instead

- source/Messaging.Infrastructure/OutgoingMessages/Peek/BundleStore.cs
Update BundleStore DequeueAsync to delete rows using SQL
> Update BundleStore DequeueAsync to delete rows using SQL

- source/Messaging.Application/Configuration/DataAccess/IUnitOfWork.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/B2BContext.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/UnitOfWork.cs
- source/Messaging.Infrastructure/Configuration/Processing/EnqueueOutgoingMessagesBehaviour.cs
- source/Messaging.Infrastructure/OutgoingMessages/EnqueuedMessageEntityConfiguration.cs
- source/Messaging.Infrastructure/OutgoingMessages/OutgoingMessageEnqueuer.cs
Register EnqueuedMessage with UnitOfWork to ensure consistency
> Register EnqueuedMessage with UnitOfWork to ensure consistency

- .github/actions/dotnet-prepare-outputs/action.yml
Publish PerformanceTest in actions/dotnet-prepare-outputs
> Publish PerformanceTest in actions/dotnet-prepare-outputs

- .github/actions/dotnet-prepare-outputs/action.yml
Rename performancetest_webapi to performancetest during publish
> Rename performancetest_webapi to performancetest during publish

- source/Messaging.PerformanceTest/Messaging.PerformanceTest.csproj
- source/Messaging.PerformanceTest/Program.cs
Add Performance Test app-service health check
> Performance test health check

- source/Messaging.Api/OutgoingMessages/PeekRequestListener.cs
- source/Messaging.Application/OutgoingMessages/Peek/IBundledMessages.cs
- source/Messaging.Application/OutgoingMessages/Peek/MessagePeeker.cs
- source/Messaging.Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/Messaging.Infrastructure/Configuration/DataAccess/B2BContext.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/BundledMessageConfiguration.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/BundledMessages.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/PeekConfiguration.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/Messaging.IntegrationTests/TestBase.cs
- source/Messaging.IntegrationTests/TestDoubles/BundledMessagesStub.cs
- Register BundledMessages in EF
- Invoke PeekHandler through a service
> Register bundledmessages with unitofwork

- source/Messaging.PerformanceTest/Program.cs
Move health endpoint from /api/monitor to /monitor
> Move health endpoint from /api/monitor to /monitor

- source/Messaging.Api/Program.cs
- source/Messaging.Api/RuntimeEnvironment.cs
Use the PERFORMANCE_TEST_ENABLED as bool in RunTimeEnvironment
> Use the  PERFORMANCE_TEST_ENABLED as bool in RunTimeEnvironment

- source/Messaging.Api/EventListeners/BalanceFixingResultAvailableEventListener.cs
Add event listener for process completed event from wholesale
> Add event listener for process completed event from wholesale

- source/Messaging.Api/EventListeners/BalanceFixingResultAvailableEventListener.cs
> Fix type-o

- source/Messaging.Api/Program.cs
Console.Writeline Authenticator
> Console.Writeline Authenticator

- source/Messaging.Infrastructure/OutgoingMessages/Peek/PeekConfiguration.cs
Bugfix: Register repository as scoped
> Bugfix: Register repository as scoped

- source/Energinet.DataHub.MarketRoles.sln
- source/LearningTests/LearningTests.csproj
- source/LearningTests/Usings.cs
- source/LearningTests/WholesaleProcessResultsApiTests.cs
Add learning tests for wholesale aggregation results API
> Add learning tests for wholesale aggregation results API

- source/Messaging.Api/setup/setupazure.ps1
Update setup azure script with added topic subscription
> Update setup azure script with added topic subscription

- source/LearningTests/WholesaleProcessResultsApiTests.cs
> Disable learning test

- .github/workflows/cd.yml
- source/LearningTests/WholesaleProcessResultsApiTests.cs
Use test filter to ignore test within namespace "LearningTests".
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/the-outlaws/839
> Use test filter

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202227101350 Alter AggregatedTimeSeriesTransactions table.sql
- source/Messaging.Domain/Transactions/Aggregations/AggregationResultForwarding.cs
- source/Messaging.Infrastructure/Transactions/AggregatedTimeSeries/AggregatedTimeSeriesTransactionEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/Aggregations/WhenAggregationOfTotalProductionIsCompletedTests.cs
Added relevant fields to B2B.AggregatedTimeSeriesTransactions
Added same fields to entity configuration
Verify field values in test
> Persist AggregationResultForwarding

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202227101351 Change Id from uniqueidentifier to string.sql
- source/Messaging.Infrastructure/Transactions/Aggregations/AggregationResultForwardingEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/Aggregations/RetrieveAggregationResultTests.cs
Refactor: Change id from uniqueidentifer to nvarchar
> Refactor: Change id from uniqueidentifer to nvarchar

- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202227101352 Add actor provided id.sql
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/ForwardMeteringPointMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/SendCustomerMasterDataToGridOperatorHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MasterDataDelivery/SetCurrentKnownCustomerMasterDataHandler.cs
- source/Messaging.Application/Transactions/MoveIn/MoveInRequestHandler.cs
- source/Messaging.Application/Transactions/MoveIn/Notifications/NotifyCurrentEnergySupplierHandler.cs
- source/Messaging.Application/Transactions/MoveIn/Notifications/NotifyGridOperatorHandler.cs
- source/Messaging.Domain/Transactions/ActorProvidedId.cs
- source/Messaging.Domain/Transactions/MoveIn/IMoveInTransactionRepository.cs
- source/Messaging.Domain/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Infrastructure/Transactions/MoveIn/MoveInTransactionRepository.cs
- source/Messaging.Infrastructure/Transactions/MoveInTransactionEntityConfiguration.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Scenario.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/WhenAConsumerHasMovedInTests.cs
- source/Messaging.Tests/Domain/Transactions/MoveIn/MoveInTransactionTests.cs
Introduce actor provided transaction id
> Introduce actor provided transaction id

- source/Messaging.Application/OutgoingMessages/IOutgoingMessageStore.cs
- source/Messaging.Infrastructure/OutgoingMessages/OutgoingMessageStore.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/DispatchCustomerMasterDataForGridOperatorTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/ForwardMeteringPointMasterDataTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/SendCustomerMasterDataToGridOperatorTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/WhenRequestedCustomerMasterDataIsReceivedTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Notifications/NotifyCurrentEnergySupplierHandlerTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Notifications/NotifyGridOperatorHandlerTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/SampleData.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/Scenario.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/WhenAConsumerHasMovedInTests.cs
- source/Messaging.IntegrationTests/Assertions/AssertOutgoingMessage.cs
> Refactor move in tests

- source/Messaging.Infrastructure/Transactions/Aggregations/AggregationResultsOverHttp.cs
Add retry logic to aggregation results HTTP service
> Add retry logic to aggregation results HTTP service

- source/Messaging.Domain/SeedWork/ValueObject.cs
- source/Processing.Application/Common/Processing/InvalidProcessManagerStateException.cs
- source/Processing.Domain/Helpers/NumberHelper.cs
- source/Processing.Domain/MeteringPoints/AccountingPoint.cs
- source/Processing.Domain/MeteringPoints/BusinessProcessException.cs
> Fix GitHub check warnings

- source/Messaging.Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Messaging.IntegrationTests/Application/Transactions/Aggregations/RetrieveAggregationResultTests.cs
- source/Messaging.IntegrationTests/Assertions/AssertOutgoingMessage.cs
Bugfix: Ensure serialization of period
> Bugfix: Ensure serialization of period
