- source/shared/messaging/source/GreenEnergyHub.Messaging/MessageTypes/Common/Transaction.cs
Transaction: Remove duplication of MRID format
When instantiating a Transaction, the class provides 3 options;
- Default Ctor
- Ctor with mrId argument
- factory method
The default ctor and the factory method both specified a specific GUID format.
To ensure that we create transactions in the same format - despite how they are constructed, let the FactoryMethod use the default ctor.
ps: transactions created with a specified mrId can still differ as the transaction does not enforce any constraints here
* #0000
> Transaction: Remove duplication of MRID format

- source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/SeedWork/Entity.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/BusinessRequestProcessing/Pipeline/DomainEventsDispatcherBehaviour.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/DomainEventDispatching/DomainEventsAccessor.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/DomainEventDispatching/DomainEventsDispatcher.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/DomainEventDispatching/IDomainEventsAccessor.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/DomainEventDispatching/IDomainEventsDispatcher.cs
- source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/TestHost.cs
This PR adds handling for domain events disparching and contains the following:
- `IDomainEventsAccessor` which enables fetching all generated domain events from the current business process scope
- `IDomainEventsDispatcher` used for dispatching domain events of to MediatR. Thus, `INotificationHandler`s are getting invoked.
- `DomainEventsDispatcherBehaviour` used for invoking `DomainEventsDispatcher` as the last step in a business process.
> Add domain events dispatch handling

- .github/dependabot.yml
While we limit dependabot to zero pull requests, it will still be able to create security updates as these have their own internal limits (10).
> limit dependabot to zero pull requests

- source/ExternalAnnotations/FluentValidation.xml
- source/ExternalAnnotations/MediatR.xml
Added ExternalAnnotations like in MeteringPoint repo. Used to make it obvious that instances registered/invoked by Open Generics and Reflection are actually in use.
* #0000
> Added ExternalAnnotations

- source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/XmlConverter/XmlMapper.cs
XmlConverter should return null if parent element for optional field is missing
* [https://github.com/Energinet-DataHub/geh-metering-point/issues/248](url)
> XmlConverter optimization

- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/DatabaseFixture.cs
- source/Energinet.DataHub.MarketRoles.IntegrationTests/Application/TestHost.cs
This PR fixes a bug where a container will be used regardless of whether or not you're running with a local database.
Use `IntegrationTests_ConnectionString` as local database name.
fixes #700
> fix: using local db shouldn't use container

- build/infrastructure/main/kv-sharedresources.tf
> Changed integration queue listener to Market Roles instead of Metering Point

- source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/CommandApi.cs
Moved correlation id to the header as per our documentation.
Also made sure that we include it on all requests and not just the successful ones.
* https://github.com/Energinet-DataHub/green-energy-hub/issues/270
> Moved correlation id to the header instead of body

- source/B2B.Transactions.Infrastructure/Configuration/Correlation/CorrelationIdMiddleware.cs
Changed GetService<CorrelationContext> to GetService<ICorrelationContext>
> Accessing service on ICorrelationContext instead of CorrelationContext

- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
Some users experience an issue with some requests being denied with a 401 status code.
This is an attempt at removing the risk of exhausting ports due to the DB instance not being a singleton (Which is recommended)
* #0000
> Changed database instance to Singleton instead of Scoped

- source/Messaging.CimMessageAdapter/Messages/MessageParser.cs
- source/Messaging.IntegrationTests/CimMessageAdapter/MessageReceiverTests.cs
- source/Messaging.IntegrationTests/CimMessageAdapter/Messages/BusinessMessageBuilder.cs
This PR fixes a problem where schema errors in the `MktActivityRecord` element did not result in a B2B-validation error.
> Fix schema validation error handling

- build/infrastructure/main/func-api.tf
- build/infrastructure/main/kv-shared-resources.tf
- source/Messaging.Api/IncomingMessages/MasterDataResponseListener.cs
- source/Messaging.Api/IncomingMessages/MeteringPointMasterDataResponseListener.cs
- source/Messaging.Api/local.settings.sample.json
Adds a new queue trigger for receiving response to master data requests from MP domain
Adds new configuration for retreiving queue name from KV
> Add queue trigger for mp response

- source/Messaging.Application/Transactions/MoveIn/MoveInTransaction.cs
- source/Messaging.Application/Transactions/MoveIn/PendingBusinessProcess.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/AssertTransaction.cs
- source/Messaging.IntegrationTests/Application/Transactions/MoveIn/CompleteMoveInTests.cs
- source/Messaging.Tests/Transactions/MoveIn/MoveInTransactionTests.cs
Set ProcessId on MoveInTransaction on transaction start
Added test to ensure ProcessId matches that of BusinessRequestResult
> Add ProcessId to Transaction

- source/Energinet.DataHub.MarketRoles.ActorRegistrySync/Services/MarketRolesDbService.cs
The stringbuilder component is currently crashing in some environments due to it containing no content when there are no supplier registrations.
Now it skips the logic all together if no supplier registrations were found.
> Added skip in case of no suppliers

- source/Messaging.CimMessageAdapter/Errors/EmptyMessageId.cs
- source/Messaging.CimMessageAdapter/Errors/EmptyTransactionId.cs
- source/Messaging.CimMessageAdapter/MessageReceiver.cs
Added error for when messageid or transactionid is empty. 
* #0000
> Throw error when transaction or messageid is empty

- .github/workflows/ci.yml
- .github/workflows/integration-events-publish.yml
Speed up CI execution time by using default .NET Core SDK version pre-installed on hosted Github Runner
Ref: https://github.com/Energinet-DataHub/the-outlaws/issues/360
> Remove DOTNET_VERSION

- source/Messaging.Application/MasterData/MarketEvaluationPoints/SetEnergySupplier.cs
- source/Messaging.Application/Transactions/MoveIn/CompleteMoveInTransaction.cs
- source/Messaging.Application/Transactions/MoveIn/FetchMeteringPointMasterData.cs
- source/Messaging.Application/Transactions/MoveIn/ForwardMeteringPointMasterData.cs
- source/Messaging.ArchitectureTests/Application/InternalCommandTests.cs
Ensure internal command constructors are decorated with JSON attribute
> Ensure internal command constructors are decorated with JSON attribute

- source/Processing.Infrastructure/BusinessRequestProcessing/Pipeline/UnitOfWorkBehaviour.cs
Two fields are not used in any codepath and can safely be removed
> Remove unused fields

- source/Messaging.Infrastructure/Configuration/InternalCommands/InternalCommandAccessor.cs
By returning a completed task we don't utilise I/O completion. This change is creating an ImmutableList the same way as the extension method `ToImmutableList()` but can use async/await keywords.
> Use async/await over Task.FromResult

- source/Messaging.Api/Program.cs
- source/Messaging.Infrastructure/Configuration/Authentication/DevMarketActorAuthenticator.cs
- source/Messaging.Infrastructure/Configuration/Authentication/MarketActorAuthenticator.cs
- source/Messaging.Infrastructure/Configuration/CompositionRoot.cs
- source/Messaging.IntegrationTests/TestBase.cs
This PR adds a test/dev version of `MarketActorAuthenticator`. This authenticator will automatically create the actor in the system, based on magic values provided in the test JWT. The following claims are required in order to automatically add a test actor to the  system:
azp: <A guid>
test-actornumber: <a GLN or EIC number>
> Add authenticator for development and test

- source/Messaging.Api/Program.cs
- source/Messaging.Api/RuntimeEnvironment.cs
Added PERFORMANCE_TEST_ENABLED environment variable.
This is used inMessaging.Api for controlling which MarketActorAuthenticator implementation to use during test
> Added PERFORMANCE_TEST_ENABLED environment variable.

- source/Messaging.PerformanceTest/MoveIn/MoveInService.cs
- source/Messaging.PerformanceTest/Program.cs
Allow use of both http and https protocol on the test-utility application service. It is allowed 
temporarily due to an certificate issue when switching from k6 to JMeter.
When calling the Messaging.Api from the PerformanceTest service determine by port number if the http/https protocol should be used.
> Performance Test: http/https protocol configuration

- source/Messaging.Api/OutgoingMessages/MessageCountRequestListener.cs
- source/Messaging.Application/Configuration/Queries/IQuery.cs
- source/Messaging.Application/Configuration/Queries/QueryResult.cs
- source/Messaging.Application/OutgoingMessages/MessageCount/MessageCountRequestHandler.cs
- source/Messaging.Infrastructure/OutgoingMessages/Peek/PeekConfiguration.cs
- source/Messaging.IntegrationTests/Application/OutgoingMessages/WhenMessageCountIsRequestedTests.cs
- source/Messaging.IntegrationTests/TestBase.cs
Perform the MessageCount using a Query instead of a Command
This avoids a transaction lock on the SQl table while getting the message count
> Perform the MessageCount using a Query instead of a Command
